local config = { 
	[1] = { 
		ID=1,
		Condition="<$LEVEL> >= 1 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 1 & <$GOODEVILID> >= 0",
		ConditionShow="级别:1",
	},
	[2] = { 
		ID=2,
		Condition="<$LEVEL> >= 2 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 2 & <$GOODEVILID> >= 0",
		ConditionShow="级别:2",
	},
	[3] = { 
		ID=3,
		Condition="<$LEVEL> >= 3 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 3 & <$GOODEVILID> >= 0",
		ConditionShow="级别:3",
	},
	[4] = { 
		ID=4,
		Condition="<$LEVEL> >= 4 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 4 & <$GOODEVILID> >= 0",
		ConditionShow="级别:4",
	},
	[5] = { 
		ID=5,
		Condition="<$LEVEL> >= 5 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 5 & <$GOODEVILID> >= 0",
		ConditionShow="级别:5",
	},
	[6] = { 
		ID=6,
		Condition="<$LEVEL> >= 6 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 6 & <$GOODEVILID> >= 0",
		ConditionShow="级别:6",
	},
	[7] = { 
		ID=7,
		Condition="<$LEVEL> >= 7 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 7 & <$GOODEVILID> >= 0",
		ConditionShow="级别:7",
	},
	[8] = { 
		ID=8,
		Condition="<$LEVEL> >= 8 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 8 & <$GOODEVILID> >= 0",
		ConditionShow="级别:8",
	},
	[9] = { 
		ID=9,
		Condition="<$LEVEL> >= 9 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 9 & <$GOODEVILID> >= 0",
		ConditionShow="级别:9",
	},
	[10] = { 
		ID=10,
		Condition="<$LEVEL> >= 10 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 10 & <$GOODEVILID> >= 0",
		ConditionShow="级别:10",
	},
	[11] = { 
		ID=11,
		Condition="<$LEVEL> >= 11 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 11 & <$GOODEVILID> >= 0",
		ConditionShow="级别:11",
	},
	[12] = { 
		ID=12,
		Condition="<$LEVEL> >= 12 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 12 & <$GOODEVILID> >= 0",
		ConditionShow="级别:12",
	},
	[13] = { 
		ID=13,
		Condition="<$LEVEL> >= 13 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 13 & <$GOODEVILID> >= 0",
		ConditionShow="级别:13",
	},
	[14] = { 
		ID=14,
		Condition="<$LEVEL> >= 14 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 14 & <$GOODEVILID> >= 0",
		ConditionShow="级别:14",
	},
	[15] = { 
		ID=15,
		Condition="<$LEVEL> >= 15 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 15 & <$GOODEVILID> >= 0",
		ConditionShow="级别:15",
	},
	[16] = { 
		ID=16,
		Condition="<$LEVEL> >= 16 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 16 & <$GOODEVILID> >= 0",
		ConditionShow="级别:16",
	},
	[17] = { 
		ID=17,
		Condition="<$LEVEL> >= 17 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 17 & <$GOODEVILID> >= 0",
		ConditionShow="级别:17",
	},
	[18] = { 
		ID=18,
		Condition="<$LEVEL> >= 18 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 18 & <$GOODEVILID> >= 0",
		ConditionShow="级别:18",
	},
	[19] = { 
		ID=19,
		Condition="<$LEVEL> >= 19 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 19 & <$GOODEVILID> >= 0",
		ConditionShow="级别:19",
	},
	[20] = { 
		ID=20,
		Condition="<$LEVEL> >= 20 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 20 & <$GOODEVILID> >= 0",
		ConditionShow="级别:20",
	},
	[21] = { 
		ID=21,
		Condition="<$LEVEL> >= 21 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 21 & <$GOODEVILID> >= 0",
		ConditionShow="级别:21",
	},
	[22] = { 
		ID=22,
		Condition="<$LEVEL> >= 22 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 22 & <$GOODEVILID> >= 0",
		ConditionShow="级别:22",
	},
	[23] = { 
		ID=23,
		Condition="<$LEVEL> >= 23 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 23 & <$GOODEVILID> >= 0",
		ConditionShow="级别:23",
	},
	[24] = { 
		ID=24,
		Condition="<$LEVEL> >= 24 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 24 & <$GOODEVILID> >= 0",
		ConditionShow="级别:24",
	},
	[25] = { 
		ID=25,
		Condition="<$LEVEL> >= 25 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 25 & <$GOODEVILID> >= 0",
		ConditionShow="级别:25",
	},
	[26] = { 
		ID=26,
		Condition="<$LEVEL> >= 26 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 26 & <$GOODEVILID> >= 0",
		ConditionShow="级别:26",
	},
	[27] = { 
		ID=27,
		Condition="<$LEVEL> >= 27 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 27 & <$GOODEVILID> >= 0",
		ConditionShow="级别:27",
	},
	[28] = { 
		ID=28,
		Condition="<$LEVEL> >= 28 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 28 & <$GOODEVILID> >= 0",
		ConditionShow="级别:28",
	},
	[29] = { 
		ID=29,
		Condition="<$LEVEL> >= 29 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 29 & <$GOODEVILID> >= 0",
		ConditionShow="级别:29",
	},
	[30] = { 
		ID=30,
		Condition="<$LEVEL> >= 30 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 30 & <$GOODEVILID> >= 0",
		ConditionShow="级别:30",
	},
	[31] = { 
		ID=31,
		Condition="<$LEVEL> >= 31 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 31 & <$GOODEVILID> >= 0",
		ConditionShow="级别:31",
	},
	[32] = { 
		ID=32,
		Condition="<$LEVEL> >= 32 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 32 & <$GOODEVILID> >= 0",
		ConditionShow="级别:32",
	},
	[33] = { 
		ID=33,
		Condition="<$LEVEL> >= 33 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 33 & <$GOODEVILID> >= 0",
		ConditionShow="级别:33",
	},
	[34] = { 
		ID=34,
		Condition="<$LEVEL> >= 34 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 34 & <$GOODEVILID> >= 0",
		ConditionShow="级别:34",
	},
	[35] = { 
		ID=35,
		Condition="<$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 35 & <$GOODEVILID> >= 0",
		ConditionShow="级别:35",
	},
	[36] = { 
		ID=36,
		Condition="<$LEVEL> >= 36 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 36 & <$GOODEVILID> >= 0",
		ConditionShow="级别:36",
	},
	[37] = { 
		ID=37,
		Condition="<$LEVEL> >= 37 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 37 & <$GOODEVILID> >= 0",
		ConditionShow="级别:37",
	},
	[38] = { 
		ID=38,
		Condition="<$LEVEL> >= 38 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 38 & <$GOODEVILID> >= 0",
		ConditionShow="级别:38",
	},
	[39] = { 
		ID=39,
		Condition="<$LEVEL> >= 39 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 39 & <$GOODEVILID> >= 0",
		ConditionShow="级别:39",
	},
	[40] = { 
		ID=40,
		Condition="<$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 40 & <$GOODEVILID> >= 0",
		ConditionShow="级别:40",
	},
	[41] = { 
		ID=41,
		Condition="<$LEVEL> >= 41 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 41 & <$GOODEVILID> >= 0",
		ConditionShow="级别:41",
	},
	[42] = { 
		ID=42,
		Condition="<$LEVEL> >= 42 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 42 & <$GOODEVILID> >= 0",
		ConditionShow="级别:42",
	},
	[43] = { 
		ID=43,
		Condition="<$LEVEL> >= 43 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 43 & <$GOODEVILID> >= 0",
		ConditionShow="级别:43",
	},
	[44] = { 
		ID=44,
		Condition="<$LEVEL> >= 44 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 44 & <$GOODEVILID> >= 0",
		ConditionShow="级别:44",
	},
	[45] = { 
		ID=45,
		Condition="<$LEVEL> >= 45 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 45 & <$GOODEVILID> >= 0",
		ConditionShow="级别:45",
	},
	[46] = { 
		ID=46,
		Condition="<$LEVEL> >= 46 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 46 & <$GOODEVILID> >= 0",
		ConditionShow="级别:46",
	},
	[47] = { 
		ID=47,
		Condition="<$LEVEL> >= 47 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 47 & <$GOODEVILID> >= 0",
		ConditionShow="级别:47",
	},
	[48] = { 
		ID=48,
		Condition="<$LEVEL> >= 48 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 48 & <$GOODEVILID> >= 0",
		ConditionShow="级别:48",
	},
	[49] = { 
		ID=49,
		Condition="<$LEVEL> >= 49 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 49 & <$GOODEVILID> >= 0",
		ConditionShow="级别:49",
	},
	[50] = { 
		ID=50,
		Condition="<$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 50 & <$GOODEVILID> >= 0",
		ConditionShow="级别:50",
	},
	[51] = { 
		ID=51,
		Condition="<$LEVEL> >= 51 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 51 & <$GOODEVILID> >= 0",
		ConditionShow="级别:51",
	},
	[52] = { 
		ID=52,
		Condition="<$LEVEL> >= 52 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 52 & <$GOODEVILID> >= 0",
		ConditionShow="级别:52",
	},
	[53] = { 
		ID=53,
		Condition="<$LEVEL> >= 53 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 53 & <$GOODEVILID> >= 0",
		ConditionShow="级别:53",
	},
	[54] = { 
		ID=54,
		Condition="<$LEVEL> >= 54 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 54 & <$GOODEVILID> >= 0",
		ConditionShow="级别:54",
	},
	[55] = { 
		ID=55,
		Condition="<$LEVEL> >= 55 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 55 & <$GOODEVILID> >= 0",
		ConditionShow="级别:55",
	},
	[56] = { 
		ID=56,
		Condition="<$LEVEL> >= 56 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 56 & <$GOODEVILID> >= 0",
		ConditionShow="级别:56",
	},
	[57] = { 
		ID=57,
		Condition="<$LEVEL> >= 57 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 57 & <$GOODEVILID> >= 0",
		ConditionShow="级别:57",
	},
	[58] = { 
		ID=58,
		Condition="<$LEVEL> >= 58 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 58 & <$GOODEVILID> >= 0",
		ConditionShow="级别:58",
	},
	[59] = { 
		ID=59,
		Condition="<$LEVEL> >= 59 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 59 & <$GOODEVILID> >= 0",
		ConditionShow="级别:59",
	},
	[60] = { 
		ID=60,
		Condition="<$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 60 & <$GOODEVILID> >= 0",
		ConditionShow="级别:60",
	},
	[61] = { 
		ID=61,
		Condition="<$LEVEL> >= 61 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 61 & <$GOODEVILID> >= 0",
		ConditionShow="级别:61",
	},
	[62] = { 
		ID=62,
		Condition="<$LEVEL> >= 62 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 62 & <$GOODEVILID> >= 0",
		ConditionShow="级别:62",
	},
	[63] = { 
		ID=63,
		Condition="<$LEVEL> >= 63 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 63 & <$GOODEVILID> >= 0",
		ConditionShow="级别:63",
	},
	[64] = { 
		ID=64,
		Condition="<$LEVEL> >= 64 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 64 & <$GOODEVILID> >= 0",
		ConditionShow="级别:64",
	},
	[65] = { 
		ID=65,
		Condition="<$LEVEL> >= 65 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 65 & <$GOODEVILID> >= 0",
		ConditionShow="级别:65",
	},
	[66] = { 
		ID=66,
		Condition="<$LEVEL> >= 66 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 66 & <$GOODEVILID> >= 0",
		ConditionShow="级别:66",
	},
	[67] = { 
		ID=67,
		Condition="<$LEVEL> >= 67 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 67 & <$GOODEVILID> >= 0",
		ConditionShow="级别:67",
	},
	[68] = { 
		ID=68,
		Condition="<$LEVEL> >= 68 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 68 & <$GOODEVILID> >= 0",
		ConditionShow="级别:68",
	},
	[69] = { 
		ID=69,
		Condition="<$LEVEL> >= 69 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 69 & <$GOODEVILID> >= 0",
		ConditionShow="级别:69",
	},
	[70] = { 
		ID=70,
		Condition="<$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 70 & <$GOODEVILID> >= 0",
		ConditionShow="级别:70",
	},
	[71] = { 
		ID=71,
		Condition="<$LEVEL> >= 71 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 71 & <$GOODEVILID> >= 0",
		ConditionShow="级别:71",
	},
	[72] = { 
		ID=72,
		Condition="<$LEVEL> >= 72 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 72 & <$GOODEVILID> >= 0",
		ConditionShow="级别:72",
	},
	[73] = { 
		ID=73,
		Condition="<$LEVEL> >= 73 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 73 & <$GOODEVILID> >= 0",
		ConditionShow="级别:73",
	},
	[74] = { 
		ID=74,
		Condition="<$LEVEL> >= 74 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 74 & <$GOODEVILID> >= 0",
		ConditionShow="级别:74",
	},
	[75] = { 
		ID=75,
		Condition="<$LEVEL> >= 75 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 75 & <$GOODEVILID> >= 0",
		ConditionShow="级别:75",
	},
	[76] = { 
		ID=76,
		Condition="<$LEVEL> >= 76 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 76 & <$GOODEVILID> >= 0",
		ConditionShow="级别:76",
	},
	[77] = { 
		ID=77,
		Condition="<$LEVEL> >= 77 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 77 & <$GOODEVILID> >= 0",
		ConditionShow="级别:77",
	},
	[78] = { 
		ID=78,
		Condition="<$LEVEL> >= 78 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 78 & <$GOODEVILID> >= 0",
		ConditionShow="级别:78",
	},
	[79] = { 
		ID=79,
		Condition="<$LEVEL> >= 79 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 79 & <$GOODEVILID> >= 0",
		ConditionShow="级别:79",
	},
	[80] = { 
		ID=80,
		Condition="<$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 80 & <$GOODEVILID> >= 0",
		ConditionShow="级别:80",
	},
	[81] = { 
		ID=81,
		Condition="<$LEVEL> >= 81 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 81 & <$GOODEVILID> >= 0",
		ConditionShow="级别:81",
	},
	[82] = { 
		ID=82,
		Condition="<$LEVEL> >= 82 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 82 & <$GOODEVILID> >= 0",
		ConditionShow="级别:82",
	},
	[83] = { 
		ID=83,
		Condition="<$LEVEL> >= 83 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 83 & <$GOODEVILID> >= 0",
		ConditionShow="级别:83",
	},
	[84] = { 
		ID=84,
		Condition="<$LEVEL> >= 84 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 84 & <$GOODEVILID> >= 0",
		ConditionShow="级别:84",
	},
	[85] = { 
		ID=85,
		Condition="<$LEVEL> >= 85 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 85 & <$GOODEVILID> >= 0",
		ConditionShow="级别:85",
	},
	[86] = { 
		ID=86,
		Condition="<$LEVEL> >= 86 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 86 & <$GOODEVILID> >= 0",
		ConditionShow="级别:86",
	},
	[87] = { 
		ID=87,
		Condition="<$LEVEL> >= 87 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 87 & <$GOODEVILID> >= 0",
		ConditionShow="级别:87",
	},
	[88] = { 
		ID=88,
		Condition="<$LEVEL> >= 88 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 88 & <$GOODEVILID> >= 0",
		ConditionShow="级别:88",
	},
	[89] = { 
		ID=89,
		Condition="<$LEVEL> >= 89 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 89 & <$GOODEVILID> >= 0",
		ConditionShow="级别:89",
	},
	[90] = { 
		ID=90,
		Condition="<$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 90 & <$GOODEVILID> >= 0",
		ConditionShow="级别:90",
	},
	[91] = { 
		ID=91,
		Condition="<$LEVEL> >= 91 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 91 & <$GOODEVILID> >= 0",
		ConditionShow="级别:91",
	},
	[92] = { 
		ID=92,
		Condition="<$LEVEL> >= 92 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 92 & <$GOODEVILID> >= 0",
		ConditionShow="级别:92",
	},
	[93] = { 
		ID=93,
		Condition="<$LEVEL> >= 93 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 93 & <$GOODEVILID> >= 0",
		ConditionShow="级别:93",
	},
	[94] = { 
		ID=94,
		Condition="<$LEVEL> >= 94 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 94 & <$GOODEVILID> >= 0",
		ConditionShow="级别:94",
	},
	[95] = { 
		ID=95,
		Condition="<$LEVEL> >= 95 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 95 & <$GOODEVILID> >= 0",
		ConditionShow="级别:95",
	},
	[96] = { 
		ID=96,
		Condition="<$LEVEL> >= 96 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 96 & <$GOODEVILID> >= 0",
		ConditionShow="级别:96",
	},
	[97] = { 
		ID=97,
		Condition="<$LEVEL> >= 97 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 97 & <$GOODEVILID> >= 0",
		ConditionShow="级别:97",
	},
	[98] = { 
		ID=98,
		Condition="<$LEVEL> >= 98 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 98 & <$GOODEVILID> >= 0",
		ConditionShow="级别:98",
	},
	[99] = { 
		ID=99,
		Condition="<$LEVEL> >= 99 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 99 & <$GOODEVILID> >= 0",
		ConditionShow="级别:99",
	},
	[100] = { 
		ID=100,
		Condition="<$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 100 & <$GOODEVILID> >= 0",
		ConditionShow="级别:100",
	},
	[101] = { 
		ID=101,
		Condition="<$LEVEL> >= 101 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 101 & <$GOODEVILID> >= 0",
		ConditionShow="级别:101",
	},
	[102] = { 
		ID=102,
		Condition="<$LEVEL> >= 102 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 102 & <$GOODEVILID> >= 0",
		ConditionShow="级别:102",
	},
	[103] = { 
		ID=103,
		Condition="<$LEVEL> >= 103 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 103 & <$GOODEVILID> >= 0",
		ConditionShow="级别:103",
	},
	[104] = { 
		ID=104,
		Condition="<$LEVEL> >= 104 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 104 & <$GOODEVILID> >= 0",
		ConditionShow="级别:104",
	},
	[105] = { 
		ID=105,
		Condition="<$LEVEL> >= 105 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 105 & <$GOODEVILID> >= 0",
		ConditionShow="级别:105",
	},
	[106] = { 
		ID=106,
		Condition="<$LEVEL> >= 106 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 106 & <$GOODEVILID> >= 0",
		ConditionShow="级别:106",
	},
	[107] = { 
		ID=107,
		Condition="<$LEVEL> >= 107 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 107 & <$GOODEVILID> >= 0",
		ConditionShow="级别:107",
	},
	[108] = { 
		ID=108,
		Condition="<$LEVEL> >= 108 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 108 & <$GOODEVILID> >= 0",
		ConditionShow="级别:108",
	},
	[109] = { 
		ID=109,
		Condition="<$LEVEL> >= 109 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 109 & <$GOODEVILID> >= 0",
		ConditionShow="级别:109",
	},
	[110] = { 
		ID=110,
		Condition="<$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 110 & <$GOODEVILID> >= 0",
		ConditionShow="级别:110",
	},
	[111] = { 
		ID=111,
		Condition="<$LEVEL> >= 111 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 111 & <$GOODEVILID> >= 0",
		ConditionShow="级别:111",
	},
	[112] = { 
		ID=112,
		Condition="<$LEVEL> >= 112 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 112 & <$GOODEVILID> >= 0",
		ConditionShow="级别:112",
	},
	[113] = { 
		ID=113,
		Condition="<$LEVEL> >= 113 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 113 & <$GOODEVILID> >= 0",
		ConditionShow="级别:113",
	},
	[114] = { 
		ID=114,
		Condition="<$LEVEL> >= 114 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 114 & <$GOODEVILID> >= 0",
		ConditionShow="级别:114",
	},
	[115] = { 
		ID=115,
		Condition="<$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 115 & <$GOODEVILID> >= 0",
		ConditionShow="级别:115",
	},
	[116] = { 
		ID=116,
		Condition="<$LEVEL> >= 116 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 116 & <$GOODEVILID> >= 0",
		ConditionShow="级别:116",
	},
	[117] = { 
		ID=117,
		Condition="<$LEVEL> >= 117 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 117 & <$GOODEVILID> >= 0",
		ConditionShow="级别:117",
	},
	[118] = { 
		ID=118,
		Condition="<$LEVEL> >= 118 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 118 & <$GOODEVILID> >= 0",
		ConditionShow="级别:118",
	},
	[119] = { 
		ID=119,
		Condition="<$LEVEL> >= 119 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 119 & <$GOODEVILID> >= 0",
		ConditionShow="级别:119",
	},
	[120] = { 
		ID=120,
		Condition="<$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 120 & <$GOODEVILID> >= 0",
		ConditionShow="级别:120",
	},
	[121] = { 
		ID=121,
		Condition="<$LEVEL> >= 121 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 121 & <$GOODEVILID> >= 0",
		ConditionShow="级别:121",
	},
	[122] = { 
		ID=122,
		Condition="<$LEVEL> >= 122 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 122 & <$GOODEVILID> >= 0",
		ConditionShow="级别:122",
	},
	[123] = { 
		ID=123,
		Condition="<$LEVEL> >= 123 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 123 & <$GOODEVILID> >= 0",
		ConditionShow="级别:123",
	},
	[124] = { 
		ID=124,
		Condition="<$LEVEL> >= 124 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 124 & <$GOODEVILID> >= 0",
		ConditionShow="级别:124",
	},
	[125] = { 
		ID=125,
		Condition="<$LEVEL> >= 125 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 125 & <$GOODEVILID> >= 0",
		ConditionShow="级别:125",
	},
	[126] = { 
		ID=126,
		Condition="<$LEVEL> >= 126 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 126 & <$GOODEVILID> >= 0",
		ConditionShow="级别:126",
	},
	[127] = { 
		ID=127,
		Condition="<$LEVEL> >= 127 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 127 & <$GOODEVILID> >= 0",
		ConditionShow="级别:127",
	},
	[128] = { 
		ID=128,
		Condition="<$LEVEL> >= 128 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 128 & <$GOODEVILID> >= 0",
		ConditionShow="级别:128",
	},
	[129] = { 
		ID=129,
		Condition="<$LEVEL> >= 129 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 129 & <$GOODEVILID> >= 0",
		ConditionShow="级别:129",
	},
	[130] = { 
		ID=130,
		Condition="<$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 130 & <$GOODEVILID> >= 0",
		ConditionShow="级别:130",
	},
	[131] = { 
		ID=131,
		Condition="<$LEVEL> >= 131 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 131 & <$GOODEVILID> >= 0",
		ConditionShow="级别:131",
	},
	[132] = { 
		ID=132,
		Condition="<$LEVEL> >= 132 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 132 & <$GOODEVILID> >= 0",
		ConditionShow="级别:132",
	},
	[133] = { 
		ID=133,
		Condition="<$LEVEL> >= 133 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 133 & <$GOODEVILID> >= 0",
		ConditionShow="级别:133",
	},
	[134] = { 
		ID=134,
		Condition="<$LEVEL> >= 134 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 134 & <$GOODEVILID> >= 0",
		ConditionShow="级别:134",
	},
	[135] = { 
		ID=135,
		Condition="<$LEVEL> >= 135 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 135 & <$GOODEVILID> >= 0",
		ConditionShow="级别:135",
	},
	[136] = { 
		ID=136,
		Condition="<$LEVEL> >= 136 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 136 & <$GOODEVILID> >= 0",
		ConditionShow="级别:136",
	},
	[137] = { 
		ID=137,
		Condition="<$LEVEL> >= 137 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 137 & <$GOODEVILID> >= 0",
		ConditionShow="级别:137",
	},
	[138] = { 
		ID=138,
		Condition="<$LEVEL> >= 138 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 138 & <$GOODEVILID> >= 0",
		ConditionShow="级别:138",
	},
	[139] = { 
		ID=139,
		Condition="<$LEVEL> >= 139 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 139 & <$GOODEVILID> >= 0",
		ConditionShow="级别:139",
	},
	[140] = { 
		ID=140,
		Condition="<$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 140 & <$GOODEVILID> >= 0",
		ConditionShow="级别:140",
	},
	[141] = { 
		ID=141,
		Condition="<$LEVEL> >= 141 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 141 & <$GOODEVILID> >= 0",
		ConditionShow="级别:141",
	},
	[142] = { 
		ID=142,
		Condition="<$LEVEL> >= 142 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 142 & <$GOODEVILID> >= 0",
		ConditionShow="级别:142",
	},
	[143] = { 
		ID=143,
		Condition="<$LEVEL> >= 143 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 143 & <$GOODEVILID> >= 0",
		ConditionShow="级别:143",
	},
	[144] = { 
		ID=144,
		Condition="<$LEVEL> >= 144 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 144 & <$GOODEVILID> >= 0",
		ConditionShow="级别:144",
	},
	[145] = { 
		ID=145,
		Condition="<$LEVEL> >= 145 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 145 & <$GOODEVILID> >= 0",
		ConditionShow="级别:145",
	},
	[146] = { 
		ID=146,
		Condition="<$LEVEL> >= 146 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 146 & <$GOODEVILID> >= 0",
		ConditionShow="级别:146",
	},
	[147] = { 
		ID=147,
		Condition="<$LEVEL> >= 147 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 147 & <$GOODEVILID> >= 0",
		ConditionShow="级别:147",
	},
	[148] = { 
		ID=148,
		Condition="<$LEVEL> >= 148 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 148 & <$GOODEVILID> >= 0",
		ConditionShow="级别:148",
	},
	[149] = { 
		ID=149,
		Condition="<$LEVEL> >= 149 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 149 & <$GOODEVILID> >= 0",
		ConditionShow="级别:149",
	},
	[150] = { 
		ID=150,
		Condition="<$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 0",
		CCondition="<$LEVEL> >= 150 & <$GOODEVILID> >= 0",
		ConditionShow="级别:150",
	},
	[10001] = { 
		ID=10001,
		Condition="<$LEVEL> >= 26|<$ABIL_1> < 9000",
	},
	[10002] = { 
		ID=10002,
		Condition="[1] | <$YEAR> == 2025",
	},
	[10003] = { 
		ID=10003,
		Condition="<$USERNAME> EQU 名字",
	},
	[20001] = { 
		ID=20001,
		Condition="<T10> == 123",
	},
	[20002] = { 
		ID=20002,
		Condition="<T10#VIP等级> == 10",
	},
	[30001] = { 
		ID=30001,
		Condition="<$KFDAY> >= 100",
		CCondition="<OPEN_SERVER_DAY> >= 100",
	},
	[40001] = { 
		ID=40001,
		Condition="<$LEVEL> >= 10 & <$LEVEL> < 30",
	},
	[40002] = { 
		ID=40002,
		Condition="<$LEVEL> >= 30",
		ConditionShow="等级大于30级",
	},
	[50001] = { 
		ID=50001,
		Condition="<$RANDOM_5> == 1",
		ConditionShow="五分之一概率",
	},
	[50002] = { 
		ID=50002,
		Condition="<$RANDOM_4> == 1",
		ConditionShow="四分之一概率",
	},
	[50003] = { 
		ID=50003,
		Condition="<$RANDOM_3> == 1",
		ConditionShow="三分之一概率",
	},
	[50004] = { 
		ID=50004,
		Condition="<$RANDOM_2> == 1",
		ConditionShow="二分之一概率",
	},
	[50005] = { 
		ID=50005,
		Condition="<$RANDOM_1> == 0",
		ConditionShow="一分之一概率",
	},
	[50006] = { 
		ID=50006,
		Condition="<$RANDOM_6> == 1",
		ConditionShow="六分之一概率",
	},
	[50007] = { 
		ID=50007,
		Condition="<$RANDOM_10> == 1",
		ConditionShow="十分之一概率",
	},
	[50008] = { 
		ID=50008,
		Condition="<$RANDOM_10> <= 3",
		ConditionShow="十分之三概率",
	},
	[50009] = { 
		ID=50009,
		Condition="<$RANDOM_5> <= 2",
		ConditionShow="五分之二概率",
	},
	[61000] = { 
		ID=61000,
		Condition="<$JOB> == 1",
	},
	[61001] = { 
		ID=61001,
		Condition="<$JOB> == 1 & <$LEVEL> >= 1 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 1 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="1",
	},
	[61002] = { 
		ID=61002,
		Condition="<$JOB> == 1 & <$LEVEL> >= 10 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 10 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="10",
	},
	[61003] = { 
		ID=61003,
		Condition="<$JOB> == 1 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 35 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[61004] = { 
		ID=61004,
		Condition="<$JOB> == 1 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 60 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[61005] = { 
		ID=61005,
		Condition="<$JOB> == 1 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 80 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[61006] = { 
		ID=61006,
		Condition="<$JOB> == 1 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 100 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[61007] = { 
		ID=61007,
		Condition="<$JOB> == 1 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 115 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[61008] = { 
		ID=61008,
		Condition="<$JOB> == 1 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 120 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[61009] = { 
		ID=61009,
		Condition="<$JOB> == 1 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 130 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[61010] = { 
		ID=61010,
		Condition="<$JOB> == 1 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 140 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[61011] = { 
		ID=61011,
		Condition="<$JOB> == 1 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 150 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[61012] = { 
		ID=61012,
		Condition="<$JOB> == 1 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 35 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[61013] = { 
		ID=61013,
		Condition="<$JOB> == 1 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 60 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[61014] = { 
		ID=61014,
		Condition="<$JOB> == 1 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 80 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[61015] = { 
		ID=61015,
		Condition="<$JOB> == 1 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 100 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[61016] = { 
		ID=61016,
		Condition="<$JOB> == 1 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 115 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[61017] = { 
		ID=61017,
		Condition="<$JOB> == 1 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 120 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[61018] = { 
		ID=61018,
		Condition="<$JOB> == 1 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 130 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[61019] = { 
		ID=61019,
		Condition="<$JOB> == 1 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 140 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[61020] = { 
		ID=61020,
		Condition="<$JOB> == 1 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 150 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[61021] = { 
		ID=61021,
		Condition="<$JOB> == 1 & <$LEVEL> >= 20 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 20 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="20",
	},
	[61022] = { 
		ID=61022,
		Condition="<$JOB> == 1 & <$LEVEL> >= 30 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 30 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="30",
	},
	[61023] = { 
		ID=61023,
		Condition="<$JOB> == 1 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 40 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[61024] = { 
		ID=61024,
		Condition="<$JOB> == 1 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 50 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[61025] = { 
		ID=61025,
		Condition="<$JOB> == 1 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 70 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[61026] = { 
		ID=61026,
		Condition="<$JOB> == 1 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 90 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[61027] = { 
		ID=61027,
		Condition="<$JOB> == 1 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 110 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[61028] = { 
		ID=61028,
		Condition="<$JOB> == 1 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 40 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[61029] = { 
		ID=61029,
		Condition="<$JOB> == 1 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 50 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[61030] = { 
		ID=61030,
		Condition="<$JOB> == 1 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 70 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[61031] = { 
		ID=61031,
		Condition="<$JOB> == 1 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 90 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[61032] = { 
		ID=61032,
		Condition="<$JOB> == 1 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 110 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[61033] = { 
		ID=61033,
		Condition="<$JOB> == 1 & <$LEVEL> >= 65",
		CCondition="<$JOB> == 1 & <$LEVEL> >= 65",
		ConditionShow="65",
	},
	[62000] = { 
		ID=62000,
		Condition="<$JOB> == 2",
		CCondition="<$JOB> == 2",
	},
	[62001] = { 
		ID=62001,
		Condition="<$JOB> == 2 & <$LEVEL> >= 1 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 1 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="1",
	},
	[62002] = { 
		ID=62002,
		Condition="<$JOB> == 2 & <$LEVEL> >= 10 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 10 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="10",
	},
	[62003] = { 
		ID=62003,
		Condition="<$JOB> == 2 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 35 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[62004] = { 
		ID=62004,
		Condition="<$JOB> == 2 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 60 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[62005] = { 
		ID=62005,
		Condition="<$JOB> == 2 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 80 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[62006] = { 
		ID=62006,
		Condition="<$JOB> == 2 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 100 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[62007] = { 
		ID=62007,
		Condition="<$JOB> == 2 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 115 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[62008] = { 
		ID=62008,
		Condition="<$JOB> == 2 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 120 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[62009] = { 
		ID=62009,
		Condition="<$JOB> == 2 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 130 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[62010] = { 
		ID=62010,
		Condition="<$JOB> == 2 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 140 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[62011] = { 
		ID=62011,
		Condition="<$JOB> == 2 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 150 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[62012] = { 
		ID=62012,
		Condition="<$JOB> == 2 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 35 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[62013] = { 
		ID=62013,
		Condition="<$JOB> == 2 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 60 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[62014] = { 
		ID=62014,
		Condition="<$JOB> == 2 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 80 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[62015] = { 
		ID=62015,
		Condition="<$JOB> == 2 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 100 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[62016] = { 
		ID=62016,
		Condition="<$JOB> == 2 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 115 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[62017] = { 
		ID=62017,
		Condition="<$JOB> == 2 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 120 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[62018] = { 
		ID=62018,
		Condition="<$JOB> == 2 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 130 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[62019] = { 
		ID=62019,
		Condition="<$JOB> == 2 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 140 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[62020] = { 
		ID=62020,
		Condition="<$JOB> == 2 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 150 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[62021] = { 
		ID=62021,
		Condition="<$JOB> == 2 & <$LEVEL> >= 20 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 20 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="20",
	},
	[62022] = { 
		ID=62022,
		Condition="<$JOB> == 2 & <$LEVEL> >= 30 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 30 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="30",
	},
	[62023] = { 
		ID=62023,
		Condition="<$JOB> == 2 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 40 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[62024] = { 
		ID=62024,
		Condition="<$JOB> == 2 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 50 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[62025] = { 
		ID=62025,
		Condition="<$JOB> == 2 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 70 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[62026] = { 
		ID=62026,
		Condition="<$JOB> == 2 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 90 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[62027] = { 
		ID=62027,
		Condition="<$JOB> == 2 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 110 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[62028] = { 
		ID=62028,
		Condition="<$JOB> == 2 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 40 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[62029] = { 
		ID=62029,
		Condition="<$JOB> == 2 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 50 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[62030] = { 
		ID=62030,
		Condition="<$JOB> == 2 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 70 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[62031] = { 
		ID=62031,
		Condition="<$JOB> == 2 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 90 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[62032] = { 
		ID=62032,
		Condition="<$JOB> == 2 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 110 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[62033] = { 
		ID=62033,
		Condition="<$JOB> == 2 & <$LEVEL> >= 65",
		CCondition="<$JOB> == 2 & <$LEVEL> >= 65",
		ConditionShow="65",
	},
	[63000] = { 
		ID=63000,
		Condition="<$JOB> == 3",
		CCondition="<$JOB> == 3",
	},
	[63001] = { 
		ID=63001,
		Condition="<$JOB> == 3 & <$LEVEL> >= 1 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 1 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="1",
	},
	[63002] = { 
		ID=63002,
		Condition="<$JOB> == 3 & <$LEVEL> >= 10 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 10 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="10",
	},
	[63003] = { 
		ID=63003,
		Condition="<$JOB> == 3 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 35 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[63004] = { 
		ID=63004,
		Condition="<$JOB> == 3 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 60 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[63005] = { 
		ID=63005,
		Condition="<$JOB> == 3 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 80 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[63006] = { 
		ID=63006,
		Condition="<$JOB> == 3 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 100 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[63007] = { 
		ID=63007,
		Condition="<$JOB> == 3 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 115 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[63008] = { 
		ID=63008,
		Condition="<$JOB> == 3 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 120 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[63009] = { 
		ID=63009,
		Condition="<$JOB> == 3 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 130 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[63010] = { 
		ID=63010,
		Condition="<$JOB> == 3 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 140 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[63011] = { 
		ID=63011,
		Condition="<$JOB> == 3 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 150 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[63012] = { 
		ID=63012,
		Condition="<$JOB> == 3 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 35 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[63013] = { 
		ID=63013,
		Condition="<$JOB> == 3 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 60 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[63014] = { 
		ID=63014,
		Condition="<$JOB> == 3 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 80 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[63015] = { 
		ID=63015,
		Condition="<$JOB> == 3 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 100 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[63016] = { 
		ID=63016,
		Condition="<$JOB> == 3 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 115 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[63017] = { 
		ID=63017,
		Condition="<$JOB> == 3 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 120 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[63018] = { 
		ID=63018,
		Condition="<$JOB> == 3 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 130 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[63019] = { 
		ID=63019,
		Condition="<$JOB> == 3 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 140 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[63020] = { 
		ID=63020,
		Condition="<$JOB> == 3 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 150 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[63021] = { 
		ID=63021,
		Condition="<$JOB> == 3 & <$LEVEL> >= 20 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 20 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="20",
	},
	[63022] = { 
		ID=63022,
		Condition="<$JOB> == 3 & <$LEVEL> >= 30 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 30 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="30",
	},
	[63023] = { 
		ID=63023,
		Condition="<$JOB> == 3 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 40 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[63024] = { 
		ID=63024,
		Condition="<$JOB> == 3 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 50 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[63025] = { 
		ID=63025,
		Condition="<$JOB> == 3 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 70 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[63026] = { 
		ID=63026,
		Condition="<$JOB> == 3 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 90 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[63027] = { 
		ID=63027,
		Condition="<$JOB> == 3 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 110 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[63028] = { 
		ID=63028,
		Condition="<$JOB> == 3 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 40 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[63029] = { 
		ID=63029,
		Condition="<$JOB> == 3 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 50 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[63030] = { 
		ID=63030,
		Condition="<$JOB> == 3 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 70 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[63031] = { 
		ID=63031,
		Condition="<$JOB> == 3 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 90 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[63032] = { 
		ID=63032,
		Condition="<$JOB> == 3 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 110 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[63033] = { 
		ID=63033,
		Condition="<$JOB> == 3 & <$LEVEL> >= 65",
		CCondition="<$JOB> == 3 & <$LEVEL> >= 65",
		ConditionShow="65",
	},
	[64000] = { 
		ID=64000,
		Condition="<$JOB> == 4",
		CCondition="<$JOB> == 4",
	},
	[64001] = { 
		ID=64001,
		Condition="<$JOB> == 4 & <$LEVEL> >= 1 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 1 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="1",
	},
	[64002] = { 
		ID=64002,
		Condition="<$JOB> == 4 & <$LEVEL> >= 10 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 10 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="10",
	},
	[64003] = { 
		ID=64003,
		Condition="<$JOB> == 4 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 35 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[64004] = { 
		ID=64004,
		Condition="<$JOB> == 4 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 60 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[64005] = { 
		ID=64005,
		Condition="<$JOB> == 4 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 80 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[64006] = { 
		ID=64006,
		Condition="<$JOB> == 4 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 100 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[64007] = { 
		ID=64007,
		Condition="<$JOB> == 4 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 115 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[64008] = { 
		ID=64008,
		Condition="<$JOB> == 4 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 120 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[64009] = { 
		ID=64009,
		Condition="<$JOB> == 4 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 130 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[64010] = { 
		ID=64010,
		Condition="<$JOB> == 4 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 140 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[64011] = { 
		ID=64011,
		Condition="<$JOB> == 4 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 150 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[64012] = { 
		ID=64012,
		Condition="<$JOB> == 4 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 35 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[64013] = { 
		ID=64013,
		Condition="<$JOB> == 4 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 60 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[64014] = { 
		ID=64014,
		Condition="<$JOB> == 4 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 80 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[64015] = { 
		ID=64015,
		Condition="<$JOB> == 4 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 100 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[64016] = { 
		ID=64016,
		Condition="<$JOB> == 4 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 115 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[64017] = { 
		ID=64017,
		Condition="<$JOB> == 4 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 120 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[64018] = { 
		ID=64018,
		Condition="<$JOB> == 4 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 130 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[64019] = { 
		ID=64019,
		Condition="<$JOB> == 4 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 140 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[64020] = { 
		ID=64020,
		Condition="<$JOB> == 4 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 150 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[64021] = { 
		ID=64021,
		Condition="<$JOB> == 4 & <$LEVEL> >= 20 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 20 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="20",
	},
	[64022] = { 
		ID=64022,
		Condition="<$JOB> == 4 & <$LEVEL> >= 30 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 30 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="30",
	},
	[64023] = { 
		ID=64023,
		Condition="<$JOB> == 4 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 40 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[64024] = { 
		ID=64024,
		Condition="<$JOB> == 4 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 50 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[64025] = { 
		ID=64025,
		Condition="<$JOB> == 4 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 70 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[64026] = { 
		ID=64026,
		Condition="<$JOB> == 4 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 90 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[64027] = { 
		ID=64027,
		Condition="<$JOB> == 4 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 110 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[64028] = { 
		ID=64028,
		Condition="<$JOB> == 4 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 40 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[64029] = { 
		ID=64029,
		Condition="<$JOB> == 4 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 50 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[64030] = { 
		ID=64030,
		Condition="<$JOB> == 4 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 70 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[64031] = { 
		ID=64031,
		Condition="<$JOB> == 4 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 90 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[64032] = { 
		ID=64032,
		Condition="<$JOB> == 4 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 110 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[64033] = { 
		ID=64033,
		Condition="<$JOB> == 4 & <$LEVEL> >= 65",
		CCondition="<$JOB> == 4 & <$LEVEL> >= 65",
		ConditionShow="65",
	},
	[65000] = { 
		ID=65000,
		Condition="<$JOB> == 5",
		CCondition="<$JOB> == 5",
	},
	[65001] = { 
		ID=65001,
		Condition="<$JOB> == 5 & <$LEVEL> >= 1 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 1 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="1",
	},
	[65002] = { 
		ID=65002,
		Condition="<$JOB> == 5 & <$LEVEL> >= 10 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 10 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="10",
	},
	[65003] = { 
		ID=65003,
		Condition="<$JOB> == 5 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 35 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[65004] = { 
		ID=65004,
		Condition="<$JOB> == 5 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 60 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[65005] = { 
		ID=65005,
		Condition="<$JOB> == 5 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 80 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[65006] = { 
		ID=65006,
		Condition="<$JOB> == 5 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 100 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[65007] = { 
		ID=65007,
		Condition="<$JOB> == 5 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 115 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[65008] = { 
		ID=65008,
		Condition="<$JOB> == 5 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 120 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[65009] = { 
		ID=65009,
		Condition="<$JOB> == 5 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 130 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[65010] = { 
		ID=65010,
		Condition="<$JOB> == 5 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 140 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[65011] = { 
		ID=65011,
		Condition="<$JOB> == 5 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 150 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[65012] = { 
		ID=65012,
		Condition="<$JOB> == 5 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 35 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[65013] = { 
		ID=65013,
		Condition="<$JOB> == 5 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 60 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[65014] = { 
		ID=65014,
		Condition="<$JOB> == 5 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 80 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[65015] = { 
		ID=65015,
		Condition="<$JOB> == 5 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 100 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[65016] = { 
		ID=65016,
		Condition="<$JOB> == 5 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 115 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[65017] = { 
		ID=65017,
		Condition="<$JOB> == 5 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 120 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[65018] = { 
		ID=65018,
		Condition="<$JOB> == 5 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 130 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[65019] = { 
		ID=65019,
		Condition="<$JOB> == 5 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 140 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[65020] = { 
		ID=65020,
		Condition="<$JOB> == 5 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 150 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[65021] = { 
		ID=65021,
		Condition="<$JOB> == 5 & <$LEVEL> >= 20 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 20 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="20",
	},
	[65022] = { 
		ID=65022,
		Condition="<$JOB> == 5 & <$LEVEL> >= 30 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 30 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="30",
	},
	[65023] = { 
		ID=65023,
		Condition="<$JOB> == 5 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 40 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[65024] = { 
		ID=65024,
		Condition="<$JOB> == 5 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 50 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[65025] = { 
		ID=65025,
		Condition="<$JOB> == 5 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 70 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[65026] = { 
		ID=65026,
		Condition="<$JOB> == 5 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 90 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[65027] = { 
		ID=65027,
		Condition="<$JOB> == 5 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 110 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[65028] = { 
		ID=65028,
		Condition="<$JOB> == 5 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 40 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[65029] = { 
		ID=65029,
		Condition="<$JOB> == 5 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 50 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[65030] = { 
		ID=65030,
		Condition="<$JOB> == 5 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 70 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[65031] = { 
		ID=65031,
		Condition="<$JOB> == 5 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 90 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[65032] = { 
		ID=65032,
		Condition="<$JOB> == 5 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 110 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[65033] = { 
		ID=65033,
		Condition="<$JOB> == 5 & <$LEVEL> >= 65",
		CCondition="<$JOB> == 5 & <$LEVEL> >= 65",
		ConditionShow="65",
	},
	[66000] = { 
		ID=66000,
		Condition="<$JOB> == 6",
		CCondition="<$JOB> == 6",
	},
	[66001] = { 
		ID=66001,
		Condition="<$JOB> == 6 & <$LEVEL> >= 1 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 1 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="1",
	},
	[66002] = { 
		ID=66002,
		Condition="<$JOB> == 6 & <$LEVEL> >= 10 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 10 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="10",
	},
	[66003] = { 
		ID=66003,
		Condition="<$JOB> == 6 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 35 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[66004] = { 
		ID=66004,
		Condition="<$JOB> == 6 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 60 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[66005] = { 
		ID=66005,
		Condition="<$JOB> == 6 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 80 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[66006] = { 
		ID=66006,
		Condition="<$JOB> == 6 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 100 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[66007] = { 
		ID=66007,
		Condition="<$JOB> == 6 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 115 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[66008] = { 
		ID=66008,
		Condition="<$JOB> == 6 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 120 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[66009] = { 
		ID=66009,
		Condition="<$JOB> == 6 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 130 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[66010] = { 
		ID=66010,
		Condition="<$JOB> == 6 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 140 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[66011] = { 
		ID=66011,
		Condition="<$JOB> == 6 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 150 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[66012] = { 
		ID=66012,
		Condition="<$JOB> == 6 & <$LEVEL> >= 35 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 35 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="35",
	},
	[66013] = { 
		ID=66013,
		Condition="<$JOB> == 6 & <$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 60 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="60",
	},
	[66014] = { 
		ID=66014,
		Condition="<$JOB> == 6 & <$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 80 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="80",
	},
	[66015] = { 
		ID=66015,
		Condition="<$JOB> == 6 & <$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 100 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="100",
	},
	[66016] = { 
		ID=66016,
		Condition="<$JOB> == 6 & <$LEVEL> >= 115 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 5",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 115 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 5",
		ConditionShow="115",
	},
	[66017] = { 
		ID=66017,
		Condition="<$JOB> == 6 & <$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 6",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 120 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 6",
		ConditionShow="120",
	},
	[66018] = { 
		ID=66018,
		Condition="<$JOB> == 6 & <$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 7",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 130 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 7",
		ConditionShow="130",
	},
	[66019] = { 
		ID=66019,
		Condition="<$JOB> == 6 & <$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 8",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 140 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 8",
		ConditionShow="140",
	},
	[66020] = { 
		ID=66020,
		Condition="<$JOB> == 6 & <$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 9",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 150 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 9",
		ConditionShow="150",
	},
	[66021] = { 
		ID=66021,
		Condition="<$JOB> == 6 & <$LEVEL> >= 20 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 20 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="20",
	},
	[66022] = { 
		ID=66022,
		Condition="<$JOB> == 6 & <$LEVEL> >= 30 & <$TARGETINFO(GOODEVILID)> >= 0 & <$TARGETINFO(RELEVEL)> >= 0",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 30 & <$GOODEVILID> >= 0 & <$RELEVEL> >= 0",
		ConditionShow="30",
	},
	[66023] = { 
		ID=66023,
		Condition="<$JOB> == 6 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 40 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[66024] = { 
		ID=66024,
		Condition="<$JOB> == 6 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 50 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[66025] = { 
		ID=66025,
		Condition="<$JOB> == 6 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 70 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[66026] = { 
		ID=66026,
		Condition="<$JOB> == 6 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 90 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[66027] = { 
		ID=66027,
		Condition="<$JOB> == 6 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 1 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 110 & <$GOODEVILID> >= 1 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[66028] = { 
		ID=66028,
		Condition="<$JOB> == 6 & <$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 40 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="40",
	},
	[66029] = { 
		ID=66029,
		Condition="<$JOB> == 6 & <$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 50 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 1",
		ConditionShow="50",
	},
	[66030] = { 
		ID=66030,
		Condition="<$JOB> == 6 & <$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 70 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 2",
		ConditionShow="70",
	},
	[66031] = { 
		ID=66031,
		Condition="<$JOB> == 6 & <$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 90 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 3",
		ConditionShow="90",
	},
	[66032] = { 
		ID=66032,
		Condition="<$JOB> == 6 & <$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 2 & <$TARGETINFO(RELEVEL)> >= 4",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 110 & <$GOODEVILID> >= 2 & <$RELEVEL> >= 4",
		ConditionShow="110",
	},
	[66033] = { 
		ID=66033,
		Condition="<$JOB> == 6 & <$LEVEL> >= 65",
		CCondition="<$JOB> == 6 & <$LEVEL> >= 65",
		ConditionShow="65",
	},
	[70001] = { 
		ID=70001,
		Condition="<$LEVEL> >= 30 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 30 & <$GOODEVILID> >= 1",
		ConditionShow="30",
	},
	[70002] = { 
		ID=70002,
		Condition="<$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 40 & <$GOODEVILID> >= 1",
		ConditionShow="40",
	},
	[70003] = { 
		ID=70003,
		Condition="<$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 50 & <$GOODEVILID> >= 1",
		ConditionShow="50",
	},
	[70004] = { 
		ID=70004,
		Condition="<$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 60 & <$GOODEVILID> >= 1",
		ConditionShow="60",
	},
	[70005] = { 
		ID=70005,
		Condition="<$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 70 & <$GOODEVILID> >= 1",
		ConditionShow="70",
	},
	[70006] = { 
		ID=70006,
		Condition="<$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 80 & <$GOODEVILID> >= 1",
		ConditionShow="80",
	},
	[70007] = { 
		ID=70007,
		Condition="<$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 90 & <$GOODEVILID> >= 1",
		ConditionShow="90",
	},
	[70008] = { 
		ID=70008,
		Condition="<$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 100 & <$GOODEVILID> >= 1",
		ConditionShow="100",
	},
	[70009] = { 
		ID=70009,
		Condition="<$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 110 & <$GOODEVILID> >= 1",
		ConditionShow="110",
	},
	[70010] = { 
		ID=70010,
		Condition="<$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 120 & <$GOODEVILID> >= 1",
		ConditionShow="120",
	},
	[70011] = { 
		ID=70011,
		Condition="<$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 130 & <$GOODEVILID> >= 1",
		ConditionShow="130",
	},
	[70012] = { 
		ID=70012,
		Condition="<$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 140 & <$GOODEVILID> >= 1",
		ConditionShow="140",
	},
	[70013] = { 
		ID=70013,
		Condition="<$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 1",
		CCondition="<$LEVEL> >= 150 & <$GOODEVILID> >= 1",
		ConditionShow="150",
	},
	[70014] = { 
		ID=70014,
		Condition="<$LEVEL> >= 30 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 30 & <$GOODEVILID> >= 2",
		ConditionShow="30",
	},
	[70015] = { 
		ID=70015,
		Condition="<$LEVEL> >= 40 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 40 & <$GOODEVILID> >= 2",
		ConditionShow="40",
	},
	[70016] = { 
		ID=70016,
		Condition="<$LEVEL> >= 50 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 50 & <$GOODEVILID> >= 2",
		ConditionShow="50",
	},
	[70017] = { 
		ID=70017,
		Condition="<$LEVEL> >= 60 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 60 & <$GOODEVILID> >= 2",
		ConditionShow="60",
	},
	[70018] = { 
		ID=70018,
		Condition="<$LEVEL> >= 70 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 70 & <$GOODEVILID> >= 2",
		ConditionShow="70",
	},
	[70019] = { 
		ID=70019,
		Condition="<$LEVEL> >= 80 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 80 & <$GOODEVILID> >= 2",
		ConditionShow="80",
	},
	[70020] = { 
		ID=70020,
		Condition="<$LEVEL> >= 90 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 90 & <$GOODEVILID> >= 2",
		ConditionShow="90",
	},
	[70021] = { 
		ID=70021,
		Condition="<$LEVEL> >= 100 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 100 & <$GOODEVILID> >= 2",
		ConditionShow="100",
	},
	[70022] = { 
		ID=70022,
		Condition="<$LEVEL> >= 110 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 110 & <$GOODEVILID> >= 2",
		ConditionShow="110",
	},
	[70023] = { 
		ID=70023,
		Condition="<$LEVEL> >= 120 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 120 & <$GOODEVILID> >= 2",
		ConditionShow="120",
	},
	[70024] = { 
		ID=70024,
		Condition="<$LEVEL> >= 130 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 130 & <$GOODEVILID> >= 2",
		ConditionShow="130",
	},
	[70025] = { 
		ID=70025,
		Condition="<$LEVEL> >= 140 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 140 & <$GOODEVILID> >= 2",
		ConditionShow="140",
	},
	[70026] = { 
		ID=70026,
		Condition="<$LEVEL> >= 150 & <$TARGETINFO(GOODEVILID)> >= 2",
		CCondition="<$LEVEL> >= 150 & <$GOODEVILID> >= 2",
		ConditionShow="150",
	},
	[80004] = { 
		ID=80004,
		Condition="<$TARGETINFO(RELEVEL)> >= 1",
		CCondition="<$TARGETINFO(RELEVEL)> >= 1",
		ConditionShow="1",
	},
	[80005] = { 
		ID=80005,
		Condition="<$TARGETINFO(RELEVEL)> >= 2",
		CCondition="<$TARGETINFO(RELEVEL)> >= 2",
		ConditionShow="2",
	},
	[80006] = { 
		ID=80006,
		Condition="<$TARGETINFO(RELEVEL)> >= 3",
		CCondition="<$TARGETINFO(RELEVEL)> >= 3",
		ConditionShow="3",
	},
	[100001] = { 
		ID=100001,
		Condition="<$LEVEL> >= 1",
		CCondition="<$LEVEL> >= 1",
		ConditionShow="等级大于1级",
	},
	[100002] = { 
		ID=100002,
		Condition="<$LEVEL> >= 30",
		CCondition="<$LEVEL> >= 30",
		ConditionShow="等级大于30级",
	},
	[100003] = { 
		ID=100003,
		Condition="<U74> > 0",
		CCondition="<U74> > 0",
		ConditionShow="有阵营",
	},
	[100004] = { 
		ID=100004,
		Condition="<U13> > 0",
		CCondition="<U13> > 0",
		ConditionShow="跨服开启中",
	},
	[110001] = { 
		ID=110001,
		Condition="<$LEVEL> >= 1 & <$LEVEL> <= 59",
		CCondition="<$LEVEL> >= 1 & <$LEVEL> <= 59 ",
		ConditionShow="1~59级",
	},
	[110002] = { 
		ID=110002,
		Condition="<$LEVEL> >= 60 & <$LEVEL> <= 99",
		CCondition="<$LEVEL> >= 60 & <$LEVEL> <= 99 ",
		ConditionShow="60~99级",
	},
	[110003] = { 
		ID=110003,
		Condition="<$LEVEL> >= 100 & <$LEVEL> <= 120",
		CCondition="<$LEVEL> >= 100 & <$LEVEL> <= 120",
		ConditionShow="100~201级",
	},
}
return config
