local config = { 
	["FreeStorage"] = { 
		k="FreeStorage",
		value=40,
		sName="免费仓库格子数",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["MaxStorage"] = { 
		k="MaxStorage",
		value=240,
		sName="最大仓库格子数",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["StoragePageCnt"] = { 
		k="StoragePageCnt",
		value=48,
		sName="每页仓库格子数",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["boCustCalcGain"] = { 
		k="boCustCalcGain",
		value=0,
		sName="开启自定义杀怪奖励计算(custcalcgain触发)",
		Group=1,
		GroupName="基础选项(1)",
		ComType=3,
		Hint="开启后不走引擎给经验值历练值 所以奖励自定义计算",
		IsServer=1,
	},
	["KillMonExpMultiple"] = { 
		k="KillMonExpMultiple",
		value=1,
		sName="杀怪经验倍率",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		Hint="人物杀怪所得经验值倍数，默认为1，此经验值以怪物数据库里的经验为基准",
		IsServer=1,
	},
	["HighLevelKillMonFixExp"] = { 
		k="HighLevelKillMonFixExp",
		value=1,
		sName="开启后高等级杀怪经验不变，同时组队经验均分",
		Group=1,
		GroupName="基础选项(1)",
		ComType=3,
		Hint="开启后高等级杀怪经验不变，同时组队经验均分",
		IsServer=1,
	},
	["HighLevelKillMonFixExpAllMap"] = { 
		k="HighLevelKillMonFixExpAllMap",
		value=1,
		sName="开启后组队全图分享经验、拾取分配",
		Group=1,
		GroupName="基础选项(1)",
		ComType=3,
		IsServer=1,
	},
	["GetGroupExpRange"] = { 
		k="GetGroupExpRange",
		value=10,
		sName="组队分享经验、拾取分配范围(全图分享关闭时生效)",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["LevelUpBatch"] = { 
		k="LevelUpBatch",
		value=10,
		sName="最高连续升级数",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		Hint="经验达到后可以连续升级控制",
		IsServer=1,
	},
	["MaxLevel"] = { 
		k="MaxLevel",
		value=255,
		sName="最高等级限制",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["KillAnimalExp"] = { 
		k="KillAnimalExp",
		value=1,
		sName="最高等级限制后杀怪经验",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["ChangeExp"] = { 
		k="ChangeExp",
		value=0,
		sName="限制changeexp",
		Group=1,
		GroupName="基础选项(1)",
		ComType=3,
		IsServer=1,
	},
	["ObtainDecay"] = { 
		k="ObtainDecay",
		value="1#900|2#800|3#700|4#600|5#500|6#400|7#300|8#200|9#100|10#0",
		sName="经验和历练衰减比例(在怪物表配置是否衰减)",
		Group=1,
		GroupName="基础选项(1)",
		ComType=1,
		Hint="格式：怪物低于当前等级多少级#原获取值的万分比",
		IsServer=1,
	},
	["GroupMembersMax"] = { 
		k="GroupMembersMax",
		value=8,
		sName="组队人数上限",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		Hint="组队成员数量",
		IsServer=1,
	},
	["GuildMembersMax"] = { 
		k="GuildMembersMax",
		value=5,
		sName="行会人数上限",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		Hint="行会可容纳人数限制",
		IsServer=1,
	},
	["StartPermission"] = { 
		k="StartPermission",
		value=10,
		sName="GM权限等级",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["PersonalTransactions"] = { 
		k="PersonalTransactions",
		value=20,
		sName="个人交易格子数量",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		Hint="个人交易格子数量上限为20",
		IsServer=1,
	},
	["DealGoldTypeId"] = { 
		k="DealGoldTypeId",
		value=2,
		sName="个人交易货币类型",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		Hint="64.8",
		IsServer=1,
	},
	["PerTradingLimit"] = { 
		k="PerTradingLimit",
		value=100000000,
		sName="单次交易货币数量上限",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		Hint="60",
		IsServer=1,
	},
	["NumberPropsMax"] = { 
		k="NumberPropsMax",
		value=99,
		sName="单次交易道具数量上限",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		Hint="12",
		IsServer=1,
	},
	["TypesPropsMax"] = { 
		k="TypesPropsMax",
		value=99,
		sName="单次交易道具种类上限",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["AuctionCountMax"] = { 
		k="AuctionCountMax",
		value=8,
		sName="个人拍卖上架格子上限",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["AuctionRecords"] = { 
		k="AuctionRecords",
		value=20,
		sName="个人拍卖记录保留数量上限",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["AuctionTimeRange"] = { 
		k="AuctionTimeRange",
		value=30,
		sName="个人拍卖记录保留时间范围（天）",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["BBRecallRange"] = { 
		k="BBRecallRange",
		value=15,
		sName="宝宝自动召唤范围",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		Hint="宝宝离开主人自动召回的范围，默认15",
		IsServer=1,
	},
	["PetMaxCount"] = { 
		k="PetMaxCount",
		value=15,
		sName="宠物数量上限",
		Group=1,
		GroupName="基础选项(1)",
		ComType=0,
		IsServer=1,
	},
	["ServerHomeMapInfo0"] = { 
		k="ServerHomeMapInfo0",
		value="101#209#314",
		sName="0号引擎应急地图配置",
		Group=2,
		GroupName="基础选项(2)",
		ComType=1,
		IsServer=1,
	},
	["WalkIntervalTime"] = { 
		k="WalkIntervalTime",
		value=160,
		sName="移动速度(移动1格的基础时间)",
		Group=2,
		GroupName="基础选项(2)",
		ComType=0,
		Hint="游戏中人物二次移动间隔时间，此参数默认单位毫秒",
		IsServer=1,
	},
	["EatItemSpeed"] = { 
		k="EatItemSpeed",
		value=200,
		sName="使用物品间隔",
		Group=2,
		GroupName="基础选项(2)",
		ComType=0,
		IsServer=1,
	},
	["ClickNpcSpeed"] = { 
		k="ClickNpcSpeed",
		value=100,
		sName="npc点击间隔",
		Group=2,
		GroupName="基础选项(2)",
		ComType=0,
		IsServer=1,
	},
	["SellItemsSpeed"] = { 
		k="SellItemsSpeed",
		value=300,
		sName="npc卖物品间隔",
		Group=2,
		GroupName="基础选项(2)",
		ComType=0,
		IsServer=1,
	},
	["OutBlockTime"] = { 
		k="OutBlockTime",
		value=3000,
		sName="脱离卡死时间(毫秒)",
		Group=2,
		GroupName="基础选项(2)",
		ComType=0,
		IsServer=1,
	},
	["JoinGuildCoolTime"] = { 
		k="JoinGuildCoolTime",
		value=0,
		sName="加入行会冷却时间(分)",
		Group=2,
		GroupName="基础选项(2)",
		ComType=0,
		IsServer=1,
	},
	["BelongTime"] = { 
		k="BelongTime",
		value=10,
		sName="Monster表中掉落规则5的首刀归属时间（秒）",
		Group=2,
		GroupName="基础选项(2)",
		ComType=0,
		IsServer=1,
	},
	["PathfindingCoordinates"] = { 
		k="PathfindingCoordinates",
		value=0,
		sName="显示自动寻路坐标点",
		Group=2,
		GroupName="基础选项(2)",
		ComType=3,
		IsServer=1,
	},
	["MiniMapFindRange"] = { 
		k="MiniMapFindRange",
		value=25,
		sName="点击小地图寻路不可行走区域后自动寻路到附近可行走点的最大范围",
		Group=2,
		GroupName="基础选项(2)",
		ComType=0,
		Hint="填写太大可能会影响性能",
		IsServer=0,
	},
	["WordMsgFColor"] = { 
		k="WordMsgFColor",
		value=218,
		sName="世界频道文字颜色",
		Group=5,
		GroupName="信息控制(1)",
		ComType=0,
		IsServer=1,
	},
	["GuildMsgFColor"] = { 
		k="GuildMsgFColor",
		value=254,
		sName="行会频道文字颜色",
		Group=5,
		GroupName="信息控制(1)",
		ComType=0,
		IsServer=1,
	},
	["GroupMsgFColor"] = { 
		k="GroupMsgFColor",
		value=251,
		sName="组队频道文字颜色",
		Group=5,
		GroupName="信息控制(1)",
		ComType=0,
		IsServer=1,
	},
	["CryMsgFColor"] = { 
		k="CryMsgFColor",
		value=253,
		sName="喊话频道文字颜色",
		Group=5,
		GroupName="信息控制(1)",
		ComType=0,
		IsServer=1,
	},
	["HearMsgFColor"] = { 
		k="HearMsgFColor",
		value=255,
		sName="附近频道文字颜色",
		Group=5,
		GroupName="信息控制(1)",
		ComType=0,
		IsServer=1,
	},
	["WhisperMsgFColor"] = { 
		k="WhisperMsgFColor",
		value=252,
		sName="私聊文字颜色",
		Group=5,
		GroupName="信息控制(1)",
		ComType=0,
		IsServer=1,
	},
	["GreenMsgFColor"] = { 
		k="GreenMsgFColor",
		value=254,
		sName="SENDMSG类型6颜色",
		Group=5,
		GroupName="信息控制(1)",
		ComType=0,
		IsServer=1,
	},
	["QvFuMsgFColor"] = { 
		k="QvFuMsgFColor",
		value=255,
		sName="区服频道文字颜色",
		Group=5,
		GroupName="信息控制(1)",
		ComType=0,
		IsServer=1,
	},
	["QvanFuMsgFColor"] = { 
		k="QvanFuMsgFColor",
		value=255,
		sName="全服频道文字颜色",
		Group=5,
		GroupName="信息控制(1)",
		ComType=0,
		IsServer=1,
	},
	["DealMsgFColor"] = { 
		k="DealMsgFColor",
		value=218,
		sName="交易频道文字颜色",
		Group=5,
		GroupName="信息控制(1)",
		ComType=0,
		IsServer=1,
	},
	["SayMsgMaxLen"] = { 
		k="SayMsgMaxLen",
		value=80,
		sName="聊天信息长度",
		Group=6,
		GroupName="信息控制(2)",
		ComType=0,
		IsServer=1,
	},
	["CanShoutMsgLevel"] = { 
		k="CanShoutMsgLevel",
		value=7,
		sName="允许喊话等级",
		Group=6,
		GroupName="信息控制(2)",
		ComType=0,
		IsServer=1,
	},
	["HanhuaInterval"] = { 
		k="HanhuaInterval",
		value=10,
		sName="喊话间隔",
		Group=6,
		GroupName="信息控制(2)",
		ComType=0,
		IsServer=1,
	},
	["TeamShoutCD"] = { 
		k="TeamShoutCD",
		value=10,
		sName="队伍喊话冷却时间",
		Group=6,
		GroupName="信息控制(2)",
		ComType=0,
		IsServer=1,
	},
	["KillByMonstDropUseItem"] = { 
		k="KillByMonstDropUseItem",
		value=0,
		sName="启用怪物杀死掉装备",
		Group=7,
		GroupName="死亡选项",
		ComType=3,
		Hint="勾选后死亡时按照每件装备的掉落率掉落,每件装备都轮询,直至掉落达到每次死亡的掉落上限",
		IsServer=1,
	},
	["KillByHumanDropUseItem"] = { 
		k="KillByHumanDropUseItem",
		value=0,
		sName="启用人物杀死掉装备",
		Group=7,
		GroupName="死亡选项",
		ComType=3,
		Hint="勾选后死亡时按照每件装备的掉落率掉落,每件装备都轮询,直至掉落达到每次死亡的掉落上限",
		IsServer=1,
	},
	["DropPlayLevel"] = { 
		k="DropPlayLevel",
		value=42,
		sName="多少级以下玩家死亡不掉装备",
		Group=7,
		GroupName="死亡选项",
		ComType=0,
		IsServer=1,
	},
	["HumMaxDropCount"] = { 
		k="HumMaxDropCount",
		value=2,
		sName="人物每次死亡掉落上限",
		Group=7,
		GroupName="死亡选项",
		ComType=0,
		Hint="控制非红名人物死亡时最多掉落几件身上物品",
		IsServer=1,
	},
	["DropEquipTriggerTakeOff"] = { 
		k="DropEquipTriggerTakeOff",
		value=0,
		sName="被杀掉装备触发脱装备触发",
		Group=7,
		GroupName="死亡选项",
		ComType=3,
		IsServer=1,
	},
	["MakeGhostTime"] = { 
		k="MakeGhostTime",
		value=300,
		sName="死尸清理间隔(秒),上限600",
		Group=7,
		GroupName="死亡选项",
		ComType=0,
		Hint="清除地上死尸时间",
		IsServer=1,
	},
	["MonOneDropGoldCount"] = { 
		k="MonOneDropGoldCount",
		value=2000,
		sName="怪物掉落金币堆的数量",
		Group=8,
		GroupName="物品选项",
		ComType=0,
		IsServer=1,
	},
	["DropGoldToPlayBag"] = { 
		k="DropGoldToPlayBag",
		value=1,
		sName="金币掉落直接进背包",
		Group=8,
		GroupName="物品选项",
		ComType=3,
		IsServer=1,
	},
	["ControlDropItem"] = { 
		k="ControlDropItem",
		value=0,
		sName="启用扔物品控制",
		Group=8,
		GroupName="物品选项",
		ComType=3,
		Hint="将对人物扔下来的物品和金币进行检查,小于指定规则的将不允许扔下来,或扔下来立即消失",
		IsServer=1,
	},
	["InSafeDisableDrop"] = { 
		k="InSafeDisableDrop",
		value=1,
		sName="启用安全区禁止扔",
		Group=8,
		GroupName="物品选项",
		ComType=3,
		Hint="打开此功能后安全区将禁止扔物品",
		IsServer=1,
	},
	["CanDropPrice"] = { 
		k="CanDropPrice",
		value=200,
		sName="扔物品控制-物品价格",
		Group=8,
		GroupName="物品选项",
		ComType=0,
		IsServer=1,
	},
	["PlayDropRange"] = { 
		k="PlayDropRange",
		value=2,
		sName="玩家扔物品范围(1-7)",
		Group=8,
		GroupName="物品选项",
		ComType=0,
		IsServer=1,
	},
	["ClearDropOnFloorItemTime"] = { 
		k="ClearDropOnFloorItemTime",
		value=180,
		sName="掉落物品清理时间(秒)",
		Group=8,
		GroupName="物品选项",
		ComType=0,
		Hint="清除地上物品时间",
		IsServer=1,
	},
	["FloorItemCanPickUpTime"] = { 
		k="FloorItemCanPickUpTime",
		value=180,
		sName="爆出物品可捡取时间(秒)",
		Group=8,
		GroupName="物品选项",
		ComType=0,
		IsServer=1,
	},
	["BagAddSendMail"] = { 
		k="BagAddSendMail",
		value=0,
		sName="背包满获得物品发邮件",
		Group=8,
		GroupName="物品选项",
		ComType=3,
		Hint="不勾选物品掉落地面或消失",
		IsServer=1,
	},
	["AutoPickRange"] = { 
		k="AutoPickRange",
		value=0,
		sName="自动拾取范围",
		Group=8,
		GroupName="物品选项",
		ComType=0,
		IsServer=1,
	},
	["PickupTime"] = { 
		k="PickupTime",
		value=500,
		sName="自动拾取间隔(毫秒)",
		Group=8,
		GroupName="物品选项",
		ComType=0,
		IsServer=1,
	},
	["AutoPickCnt"] = { 
		k="AutoPickCnt",
		value=20,
		sName="自动拾取数量",
		Group=8,
		GroupName="物品选项",
		ComType=0,
		IsServer=1,
	},
	["ItemDropSource"] = { 
		k="ItemDropSource",
		value=0,
		sName="记录物品来源",
		Group=8,
		GroupName="物品选项",
		ComType=3,
		IsServer=1,
	},
	["ItemSplit"] = { 
		k="ItemSplit",
		value=1,
		sName="物品拆分",
		Group=8,
		GroupName="物品选项",
		ComType=3,
		IsServer=1,
	},
	["guild_create"] = { 
		k="guild_create",
		value="1#30000",
		sName="创建行会需要的物品 物品id#数量&物品id#数量",
		Group=9,
		GroupName="功能控制",
		ComType=1,
		IsServer=1,
	},
	["guild_Rank"] = { 
		k="guild_Rank",
		value="0#帮主#1&1#副帮主#2&2#长老#200&3#精英#200&4#成员#200",
		sName="职位编号#职位名称#职位数量#权限权限0无权限1同意申请2踢人4任命8邀请16修改门派名称32修改门派公告64入会设置",
		Group=9,
		GroupName="功能控制",
		ComType=1,
		IsServer=1,
	},
	["guild_RankSet"] = { 
		k="guild_RankSet",
		value=1,
		sName="是否在游戏中开启权限设置入口，0关闭，1开启",
		Group=9,
		GroupName="功能控制",
		ComType=3,
		IsServer=1,
	},
	["guild_Close"] = { 
		k="guild_Close",
		value=1,
		sName="启用解散行会功能",
		Group=9,
		GroupName="功能控制",
		ComType=3,
		IsServer=1,
	},
	["guild_Join"] = { 
		k="guild_Join",
		value=0,
		sName="门派人满后是否能继续申请，0不能1可以",
		Group=9,
		GroupName="功能控制",
		ComType=3,
		IsServer=1,
	},
	["GuildAutoJoinLv"] = { 
		k="GuildAutoJoinLv",
		value=35,
		sName="默认申请等级",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["GuildFilterGoodEvild"] = { 
		k="GuildFilterGoodEvild",
		value=1,
		sName="门派是否只能同阵营加入 默认关闭，0关闭，1开启",
		Group=9,
		GroupName="功能控制",
		ComType=3,
		IsServer=1,
	},
	["iRefreshSortType"] = { 
		k="iRefreshSortType",
		value=1,
		sName="排行榜刷新设置：类型(0=每天定时,1=间隔xx分)",
		Group=9,
		GroupName="功能控制",
		ComType=2,
		Desc="0#1",
		IsServer=1,
	},
	["iSortEveryDayHour"] = { 
		k="iSortEveryDayHour",
		value=0,
		sName="排行榜刷新设置：小时(0-23),类型=0时生效",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["iSortEveryDayMinute"] = { 
		k="iSortEveryDayMinute",
		value=0,
		sName="排行榜刷新设置：分钟(0-59),类型=0时生效",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["iSortMinute"] = { 
		k="iSortMinute",
		value=1,
		sName="排行榜刷新设置：间隔分刷数(单位分钟),类型=1时生效",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["MaxPaimaiCount"] = { 
		k="MaxPaimaiCount",
		value=8,
		sName="拍卖行上架上限  默认为8格（不填为8）",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["PaimaiShopCloseTime"] = { 
		k="PaimaiShopCloseTime",
		value=30,
		sName="摆摊时间",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["PaimaiShopCloseTimeNoItem"] = { 
		k="PaimaiShopCloseTimeNoItem",
		value=20,
		sName="无道具摆摊关闭时间",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["PaimaiMoneyCnt"] = { 
		k="PaimaiMoneyCnt",
		value="1#100000#500|2#20000#250",
		sName="摆摊上架货币字段",
		Group=9,
		GroupName="功能控制",
		ComType=1,
		IsServer=1,
	},
	["PaimaiDefEffId"] = { 
		k="PaimaiDefEffId",
		value=200019,
		sName="摆摊摊位特效ID",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["BaiTanMax"] = { 
		k="BaiTanMax",
		value=10,
		sName="摆摊上架上限",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["BaiTanRadius"] = { 
		k="BaiTanRadius",
		value=1,
		sName="单个摊位半径（半径内不可重复摆摊）",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["BaitanRemoteBuy"] = { 
		k="BaitanRemoteBuy",
		value=1,
		sName="是否开启摆摊远程购买的开关",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["BaitanCollect"] = { 
		k="BaitanCollect",
		value=30,
		sName="摆摊收藏摊位的上限（最大50个）",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["BaiTanLog"] = { 
		k="BaiTanLog",
		value="%sx%s售出成功，收款%sx%s",
		sName="摆摊默认记录，参数依次为：道具名、道具数量、货币名、货币数量（对应EventLog表中的EventStr字段格式，不填的话可以用脚本通过EventLog表进行自定义）",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["IsOpenFashion"] = { 
		k="IsOpenFashion",
		value=0,
		sName="角色装备界面中的切换显示披风开关的默认设置，0原装、1披风",
		Group=9,
		GroupName="功能控制",
		ComType=0,
		IsServer=1,
	},
	["TeamCap"] = { 
		k="TeamCap",
		value=1,
		sName="队长退队自动转移队长",
		Group=11,
		GroupName="功能控制(2)",
		ComType=3,
		IsServer=1,
	},
	["CaptainOffline"] = { 
		k="CaptainOffline",
		value=1,
		sName="组队中下线是否自动退队（默认1退队）",
		Group=11,
		GroupName="功能控制(2)",
		ComType=3,
		IsServer=1,
	},
	["AutoChangeGuildMasterTime"] = { 
		k="AutoChangeGuildMasterTime",
		value=72,
		sName="会长离线超过xx小时，系统自动转让会长，转让规则悬停查看",
		Group=11,
		GroupName="功能控制(2)",
		ComType=0,
		Hint="如果没有副会长或副会长离线超过72小时，则自动转让给24小时内登录过游戏且等级最高的玩家",
		IsServer=1,
	},
	["HttpPostTime"] = { 
		k="HttpPostTime",
		value=0,
		sName="httppost时间(毫秒)",
		Group=12,
		GroupName="系统参数",
		ComType=0,
		IsServer=1,
	},
	["ScriptGotoCountLimit"] = { 
		k="ScriptGotoCountLimit",
		value=200,
		sName="脚本goto循环最大次数",
		Group=12,
		GroupName="系统参数",
		ComType=0,
		IsServer=1,
	},
	["SaveLuaInstance"] = { 
		k="SaveLuaInstance",
		value=1,
		sName="保留Lua虚拟机",
		Group=12,
		GroupName="系统参数",
		ComType=3,
		IsServer=1,
	},
	["HumViewRange"] = { 
		k="HumViewRange",
		value=5,
		sName="视野范围(1-5,默认3)",
		Group=12,
		GroupName="系统参数",
		ComType=0,
		IsServer=1,
	},
	["NewKfDay"] = { 
		k="NewKfDay",
		value=1,
		sName="勾选=按自然天数计算，不勾选按运行24小时计算",
		Group=12,
		GroupName="系统参数",
		ComType=3,
		IsServer=1,
	},
	["Arrow_equipment"] = { 
		k="Arrow_equipment",
		value=11,
		sName="箭矢装备的位置（ItemEquipPos表里的id）",
		Group=12,
		GroupName="系统参数",
		ComType=1,
		IsServer=1,
	},
	["attackglobalCD"] = { 
		k="attackglobalCD",
		value=100,
		sName="技能公共CD配置时间间隔默认为0 单位：毫秒",
		Group=12,
		GroupName="系统参数",
		ComType=0,
		IsServer=1,
	},
	["IgnorMongenByBlock"] = { 
		k="IgnorMongenByBlock",
		value=1,
		sName="1=怪物刷在阻挡点内，重置之后刷新",
		Group=12,
		GroupName="系统参数",
		ComType=0,
		IsServer=1,
	},
	["CanAttackNoCompPalyer"] = { 
		k="CanAttackNoCompPalyer",
		value=1,
		sName="0不允许攻击未加入阵营玩家（1默认允许攻击未加入阵营玩家）",
		Group=12,
		GroupName="系统参数",
		ComType=3,
		IsServer=1,
	},
	["RJFirendAttackMode"] = { 
		k="RJFirendAttackMode",
		value=1,
		sName="热江辅助类技能攻击模式（0传奇模式，1热江模式）",
		Group=12,
		GroupName="系统参数",
		ComType=3,
		IsServer=1,
	},
	["KuafuGoHomeMap"] = { 
		k="KuafuGoHomeMap",
		value=101,
		sName="跨服应急回城地图",
		Group=13,
		GroupName="跨服参数",
		ComType=1,
		Hint="跨服应急回城地图",
		IsServer=1,
	},
	["KuafuGoHomeX"] = { 
		k="KuafuGoHomeX",
		value=205,
		sName="跨服应急回城地图X坐标",
		Group=13,
		GroupName="跨服参数",
		ComType=1,
		Hint="跨服应急回城地图X坐标",
		IsServer=1,
	},
	["KuafuGoHomeY"] = { 
		k="KuafuGoHomeY",
		value=275,
		sName="跨服应急回城地图Y坐标",
		Group=13,
		GroupName="跨服参数",
		ComType=1,
		Hint="跨服应急回城地图Y坐标",
		IsServer=1,
	},
	["KuafuGoHomeRan"] = { 
		k="KuafuGoHomeRan",
		value=3,
		sName="跨服应急回城范围",
		Group=13,
		GroupName="跨服参数",
		ComType=0,
		Hint="跨服应急回城范围",
		IsServer=1,
	},
	["itemSacle"] = { 
		k="itemSacle",
		value="1.0|1.0",
		sName="移动端道具Icon缩放（默认1.3）|PC端道具Icon缩放（默认1.0）",
		GroupName="客户端使用",
		IsServer=0,
	},
	["showStoreBuyTips"] = { 
		k="showStoreBuyTips",
		value=1,
		sName="0不显示购买成功弹窗 1显示",
		GroupName="客户端使用",
		IsServer=0,
	},
	["DefaultChat"] = { 
		k="DefaultChat",
		value="欢迎来到热血江湖",
		sName="上线聊天频道默认显示",
		GroupName="客户端使用",
		IsServer=0,
	},
	["announce"] = { 
		k="announce",
		value="欢迎加入！",
		sName="默认公告",
		GroupName="客户端使用",
		IsServer=0,
	},
	["loadingmusic"] = { 
		k="loadingmusic",
		value=302,
		sName="登录背景音乐",
		GroupName="客户端使用",
		IsServer=0,
	},
	["loadingLogin"] = { 
		k="loadingLogin",
		value="login_1|1",
		sName="登录背景图片（背景图片资源名（可多个）|是否随机：0，不随机；1，随机切换）",
		GroupName="客户端使用",
		IsServer=0,
	},
	["loadingGame"] = { 
		k="loadingGame",
		value="login_1#login_2#login_3|1",
		sName="进入游戏背景图片（背景图片资源名（可多个）|是否随机：0，不随机；1，随机切换）",
		GroupName="客户端使用",
		IsServer=0,
	},
	["loadingScene"] = { 
		k="loadingScene",
		value="login_1|1",
		sName="场景背景图片（背景图片资源名（可多个）|是否随机：0，不随机；1，随机切换）备用",
		GroupName="客户端使用",
		IsServer=0,
	},
	["skillKeyCount"] = { 
		k="skillKeyCount",
		value=8,
		sName="技能键位数量",
		GroupName="客户端使用",
		IsServer=0,
	},
	["SFX_FLY_IN"] = { 
		k="SFX_FLY_IN",
		value="9000018#1.5|9000024#1.5|9000020#1.5|9000022#1.5",
		sName="传送进来特效（职业1|职业2|职业3|职业4）",
		GroupName="客户端使用",
		IsServer=0,
	},
	["SFX_FLY_OUT"] = { 
		k="SFX_FLY_OUT",
		value="9000017|9000023|9000019|9000021",
		sName="传送出去特效（职业1|职业2|职业3|职业4）",
		GroupName="客户端使用",
		IsServer=0,
	},
	["MouseMove"] = { 
		k="MouseMove",
		value=1,
		sName="是否启用点击地面移动, 0:不启用, 1:启用",
		GroupName="客户端使用",
		IsServer=0,
	},
	["StorePageName"] = { 
		k="StorePageName",
		value="1#装饰|2#补给|3#强化|4#好友|5#限量",
		sName="商城页签名 组别ID#商城名|",
		GroupName="客户端使用",
	},
	["PickItemFx"] = { 
		k="PickItemFx",
		value="402014#0.3#1#0",
		sName="拾取特效id#特效持续时间#抛物线高度#是否飞入背包UI",
		GroupName="客户端使用",
	},
	["ReconnectText"] = { 
		k="ReconnectText",
		value="可能出现以下问题:<br></br><font color='#F2A636'> 1.账号重复登录了<br></br> 2.你的网络不稳定，掉线了<br></br> 3.服务器进行维护中 </font>",
		sName="断线重连弹窗提示文本",
		GroupName="客户端使用",
		IsServer=0,
	},
	["DelayAutoFight"] = { 
		k="DelayAutoFight",
		value=0.1,
		sName="自动战斗中玩家移动操作X秒后继续自动战斗,不填默认0.1s",
		GroupName="客户端使用",
		IsServer=0,
	},
	["ChangeTargetDistance"] = { 
		k="ChangeTargetDistance",
		value=20,
		sName="切换目标功能中检测目标的距离",
		GroupName="客户端使用",
		ComType=0,
		Hint="切换目标功能中检测目标的距离",
	},
	["TeamCondition"] = { 
		k="TeamCondition",
		value="40001#特殊条件1|40002#特殊条件2",
		sName="进队特殊条件（条件1|条件2）",
		GroupName="客户端使用",
		Hint="条件表ID",
		IsServer=0,
	},
	["loginRole3D"] = { 
		k="loginRole3D",
		value=1,
		sName="设置选角界面是否为3D界面，1为3D，0为2D",
	},
	["BagPosRecord"] = { 
		k="BagPosRecord",
		value=1,
		sName="是否记录背包物品位置，0:不记录 1:记录",
		GroupName="客户端使用",
	},
	["ScreenReload"] = { 
		k="ScreenReload",
		value=1,
		sName="启用切换画质需重载游戏功能",
		GroupName="客户端使用",
		ComType=0,
		IsServer=0,
	},
	["DieSoundCD"] = { 
		k="DieSoundCD",
		value=1,
		sName="怪物死亡音效的公共CD，单位为秒",
	},
	["SpeakerType"] = { 
		k="SpeakerType",
		value="12|13",
		sName="聊天界面中喇叭显示的种类，例：全服狮子吼|跨服狮子吼为12|13",
		GroupName="客户端使用",
		IsServer=0,
	},
	["BackpackTab"] = { 
		k="BackpackTab",
		value="全部|装备|道具|材料|合成石|其他",
		sName="第一二个为默认，往后对应item表ItemType字段里的1、2、3、4",
		GroupName="客户端使用",
		IsServer=0,
	},
	["BackpackGridMax"] = { 
		k="BackpackGridMax",
		value=392,
		sName="背包显示最大格子数量",
		GroupName="客户端使用",
		IsServer=0,
	},
	["SectPrecautions"] = { 
		k="SectPrecautions",
		value="门主可以将职位转让给任意在线门派成员。",
		sName="门派注意事项",
		GroupName="客户端使用",
		IsServer=0,
	},
	["ForcedPickUp"] = { 
		k="ForcedPickUp",
		value=1,
		sName="自动拾取，默认1拾取",
		GroupName="客户端使用",
		IsServer=0,
	},
	["StayTimePickUp"] = { 
		k="StayTimePickUp",
		value=100,
		sName="等待拾取时间（单位：ms）",
		GroupName="客户端使用",
		IsServer=0,
	},
	["EquipmentScheme"] = { 
		k="EquipmentScheme",
		value=3,
		sName="装备方案数量，最低为1，最多为3",
		GroupName="客户端使用",
		IsServer=0,
	},
	["BagMoneyList"] = { 
		k="BagMoneyList",
		value="1#9#17#2",
		sName="背包货币列表",
		GroupName="客户端使用",
		IsServer=0,
	},
	["TreasureMoneyList"] = { 
		k="TreasureMoneyList",
		value="9#17#2#5",
		sName="百宝阁界面货币列表",
		GroupName="客户端使用",
		IsServer=0,
	},
	["NPCStoreMoneyList"] = { 
		k="NPCStoreMoneyList",
		value="1#9#17#2",
		sName="npc商店货币列表",
		GroupName="客户端使用",
		IsServer=0,
	},
	["NPCStoreMoneySell"] = { 
		k="NPCStoreMoneySell",
		value=1,
		sName="npc商店出售货币id",
		GroupName="客户端使用",
		IsServer=0,
	},
	["HUDPlayerNameSize"] = { 
		k="HUDPlayerNameSize",
		value=24,
		sName="角色名字大小  ",
		GroupName="客户端使用",
		IsServer=0,
	},
	["HUDPlayerGuildSize"] = { 
		k="HUDPlayerGuildSize",
		value=20,
		sName="行会名字大小",
		GroupName="客户端使用",
		IsServer=0,
	},
	["HUDPlayerGuildColorID"] = { 
		k="HUDPlayerGuildColorID",
		value=255,
		sName="行会名字颜色  0-255",
		GroupName="客户端使用",
		IsServer=0,
	},
	["MainPlayerNameColorID"] = { 
		k="MainPlayerNameColorID",
		value=250,
		sName="角色自己名字颜色",
		GroupName="客户端使用",
		IsServer=0,
	},
	["SaveFriendChat"] = { 
		k="SaveFriendChat",
		value=1,
		sName="是否保存好友私聊内容到本地，0不保存，1保存",
		GroupName="客户端使用",
		IsServer=0,
	},
	["QuickBar1"] = { 
		k="QuickBar1",
		value="101|102|118|119|120|123",
		sName="快捷栏1号道具，填写道具id",
		GroupName="客户端使用",
		IsServer=0,
	},
	["QuickBar2"] = { 
		k="QuickBar2",
		value="107|108|109|110|111|115|117",
		sName="快捷栏2号道具，填写道具id",
		GroupName="客户端使用",
		IsServer=0,
	},
	["QuickBar3"] = { 
		k="QuickBar3",
		value="173|174|123|435",
		sName="快捷栏3号道具，填写道具id",
		GroupName="客户端使用",
		IsServer=0,
	},
	["QuickBar4"] = { 
		k="QuickBar4",
		value="207|117|436",
		sName="快捷栏4号道具，填写道具id",
		GroupName="客户端使用",
		IsServer=0,
	},
	["ItemQuality"] = { 
		k="ItemQuality",
		value="0#凡品#FCF4CE|1#下品#00FF00|2#中品#0099FF|3#上品#9900CC|4#极品#F49C4C|5#神品#FF0000",
		sName="道具装备品质名称",
		GroupName="客户端使用",
		IsServer=0,
	},
	["bangdingguize"] = { 
		k="bangdingguize",
		value="1#3",
		sName="道具绑定模式，1模式：1#xxx xxx规则里包含item表Article里填的规则时，道具为绑定道具，2模式：2#xxx item表Article里填的规则完全包含xxx规则时，道具为绑定道具",
		GroupName="客户端使用",
		IsServer=0,
	},
	["NpcTalkBubble"] = { 
		k="NpcTalkBubble",
		value=4,
		sName="npc对话气泡弹出距离，默认为3",
		GroupName="客户端使用",
		IsServer=0,
	},
	["MobileChannelShow"] = { 
		k="MobileChannelShow",
		value="0#7#11#2#13#9#4#5#12#10",
		sName="聊天频道排序，只显示填写的频道，顺序按照填写的从上到下排列0综合、7世界、11全服、2附近、13交易、9系统、4组队、5门派、10区服、12跨服",
		GroupName="客户端使用",
		IsServer=0,
	},
	["CameraRotate"] = { 
		k="CameraRotate",
		value=0.35,
		sName="智能视角摄像机旋转速度（建议0.1-1）",
		GroupName="客户端使用",
		IsServer=0,
	},
	["UseCountdown"] = { 
		k="UseCountdown",
		value=5,
		sName="装备快捷使用栏的倒计时，单位：秒",
		GroupName="客户端使用",
		IsServer=0,
	},
	["DefaultTeamLevelMin"] = { 
		k="DefaultTeamLevelMin",
		value=1,
		sName="组队设置中默认最小等级",
		GroupName="客户端使用",
		IsServer=0,
	},
	["DefaultTeamLevelMax"] = { 
		k="DefaultTeamLevelMax",
		value=100,
		sName="组队设置中默认最大等级",
		GroupName="客户端使用",
		IsServer=0,
	},
	["ComboPointId"] = { 
		k="ComboPointId",
		value=74,
		sName="刺客连击点显示属性ID",
		GroupName="客户端使用",
		IsServer=0,
	},
	["PickMode"] = { 
		k="PickMode",
		value=0,
		sName="拾取模式 1=需要手动按拾取按钮捡取 0=站上可捡取",
		GroupName="客户端使用",
		IsServer=0,
	},
	["ChatHistoryMax"] = { 
		k="ChatHistoryMax",
		value=20,
		sName="聊天历史本地缓存数量（每个频道最大20）",
		GroupName="客户端使用",
		IsServer=0,
	},
	["ChatHistoryChannel"] = { 
		k="ChatHistoryChannel",
		value="7#11#2#13#9#12#10#1",
		sName="聊天历史本地缓存频道 #分割 7世界、11全服、2附近、13交易、9系统、4组队、5门派、10区服、12跨服、1私聊",
		GroupName="客户端使用",
		IsServer=0,
	},
	["lookPlayerMode"] = { 
		k="lookPlayerMode",
		value=1,
		sName="查看别人时的面板显示，0单装备面板，1装备+属性面板",
		GroupName="客户端使用",
		IsServer=0,
	},
	["CHATCDS"] = { 
		k="CHATCDS",
		value="7_1#11_1#2_1#13_1#9_1#4_1#5_1#10_1#12_1",
		sName="聊天频道发送CD，频道id1_时间#频道id2_时间...（时间单位：秒）",
		GroupName="客户端使用",
		IsServer=0,
	},
	["KuafuPrefix"] = { 
		k="KuafuPrefix",
		value="1#[跨]#01fa01",
		sName="跨服时，场景中显示的跨服前缀，模式1：1#前缀#字体颜色，模式2：2#图片名字（放hud路径下）#偏移x#偏移y",
		GroupName="客户端使用",
		IsServer=0,
	},
	["KuafuPrefix_UI"] = { 
		k="KuafuPrefix_UI",
		value="01fa01#[跨]",
		sName="跨服时，界面上的跨服前缀,文字颜色#文字",
		GroupName="客户端使用",
		IsServer=0,
	},
	["MainPlayerSufferClearTime"] = { 
		k="MainPlayerSufferClearTime",
		value=30,
		sName="目标功能中攻击者停手一定时间后移出列表（主玩家承伤清理cd）",
		GroupName="客户端使用",
		IsServer=0,
	},
	["QuickUseTipsShow"] = { 
		k="QuickUseTipsShow",
		value=1,
		sName="自动穿装备提示",
	},
}
return config
