local config = { 
	[1] = { 
		ID=1,
		Name="0-10级装备",
		Type=0,
		ConditionType=1,
		Condition={0,10},
		Effect={1},
		Default=1,
	},
	[2] = { 
		ID=2,
		Name="11-20级装备",
		Type=0,
		ConditionType=1,
		Condition={10,20},
		Effect={1},
		Default=1,
	},
	[3] = { 
		ID=3,
		Name="21-30级装备",
		Type=0,
		ConditionType=1,
		Condition={20,30},
		Effect={1},
		Default=1,
	},
	[4] = { 
		ID=4,
		Name="31-40级装备",
		Type=0,
		ConditionType=1,
		Condition={30,40},
		Effect={1},
		Default=1,
	},
	[5] = { 
		ID=5,
		Name="41-50级装备",
		Type=0,
		ConditionType=1,
		Condition={40,50},
		Effect={1},
		Default=1,
	},
	[6] = { 
		ID=6,
		Name="51-60级装备",
		Type=0,
		ConditionType=1,
		Condition={50,60},
		Effect={1},
		Default=1,
	},
	[7] = { 
		ID=7,
		Name="61-70级装备",
		Type=0,
		ConditionType=1,
		Condition={60,70},
		Effect={1},
		Default=1,
	},
	[8] = { 
		ID=8,
		Name="71-80级装备",
		Type=0,
		ConditionType=1,
		Condition={70,80},
		Effect={1},
		Default=1,
	},
	[9] = { 
		ID=9,
		Name="81-90级装备",
		Type=0,
		ConditionType=1,
		Condition={80,90},
		Effect={1},
		Default=0,
	},
	[10] = { 
		ID=10,
		Name="91-100级装备",
		Type=0,
		ConditionType=1,
		Condition={90,100},
		Effect={1},
		Default=0,
	},
	[11] = { 
		ID=11,
		Name="101-110级装备",
		Type=0,
		ConditionType=1,
		Condition={100,110},
		Effect={1},
		Default=0,
	},
	[12] = { 
		ID=12,
		Name="111-120级装备",
		Type=0,
		ConditionType=1,
		Condition={110,120},
		Effect={1},
		Default=0,
	},
	[13] = { 
		ID=13,
		Name="121-130级装备",
		Type=0,
		ConditionType=1,
		Condition={120,130},
		Effect={1},
		Default=0,
	},
	[14] = { 
		ID=14,
		Name="131-140级装备",
		Type=0,
		ConditionType=1,
		Condition={130,140},
		Effect={1},
		Default=0,
	},
	[15] = { 
		ID=15,
		Name="141-150级装备",
		Type=0,
		ConditionType=1,
		Condition={140,150},
		Effect={1},
		Default=0,
	},
	[16] = { 
		ID=16,
		Name="凡品",
		Type=1,
		ConditionType=2,
		Condition=0,
		Effect={1},
		Default=0,
	},
	[17] = { 
		ID=17,
		Name="下品",
		Type=1,
		ConditionType=2,
		Condition=1,
		Effect={1},
		Default=0,
	},
	[18] = { 
		ID=18,
		Name="中品",
		Type=1,
		ConditionType=2,
		Condition=2,
		Effect={1},
		Default=0,
	},
	[19] = { 
		ID=19,
		Name="上品",
		Type=1,
		ConditionType=2,
		Condition=3,
		Effect={1},
		Default=0,
	},
	[20] = { 
		ID=20,
		Name="极品",
		Type=1,
		ConditionType=2,
		Condition=4,
		Effect={1},
		Default=0,
	},
	[21] = { 
		ID=21,
		Name="神品",
		Type=1,
		ConditionType=2,
		Condition=5,
		Effect={1},
		Default=0,
	},
	[22] = { 
		ID=22,
		Name="首饰",
		Type=1,
		ConditionType=3,
		Condition={22,23,19,20,21,15},
		Effect={1},
		Default=0,
	},
	[23] = { 
		ID=23,
		Name="非本职业装备",
		Type=1,
		ConditionType=4,
		Effect={1},
		Default=1,
	},
	[24] = { 
		ID=24,
		Name="高于等级回收",
		Type=1,
		ConditionType=5,
		Effect={1},
		Default=0,
	},
	[25] = { 
		ID=25,
		Name="箭矢",
		Type=1,
		ConditionType=3,
		Condition={52},
		Effect={1},
		Default=0,
	},
	[26] = { 
		ID=26,
		Name="金刚石",
		Type=2,
		ConditionType=7,
		Condition={36,37,38,39,40},
		Effect={2},
		Default=0,
	},
	[27] = { 
		ID=27,
		Name="寒玉石",
		Type=2,
		ConditionType=7,
		Condition={30,31,32,33,34,35},
		Effect={2},
		Default=0,
	},
	[28] = { 
		ID=28,
		Name="热血石",
		Type=2,
		ConditionType=7,
		Condition={41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80},
		Effect={2},
		Default=0,
	},
	[29] = { 
		ID=29,
		Name="混元金刚石",
		Type=2,
		ConditionType=7,
		Condition={81,82,83,84,85},
		Effect={2},
		Default=0,
	},
	[30] = { 
		ID=30,
		Name="冰魄寒玉石",
		Type=2,
		ConditionType=7,
		Condition={86,87,88,89,90},
		Effect={2},
		Default=0,
	},
	[36] = { 
		ID=36,
		Name="金刚石(攻击)",
		Type=3,
		ConditionType=8,
		Condition={{1,1},{1,2},{1,3}},
		Effect={2},
		Default=0,
	},
	[37] = { 
		ID=37,
		Name="金刚石(追伤)",
		Type=3,
		ConditionType=8,
		Condition={{1,1},{1,2},{1,3}},
		Effect={2},
		Default=0,
	},
	[38] = { 
		ID=38,
		Name="金刚石(武功)",
		Type=3,
		ConditionType=8,
		Condition={{1,1},{1,2},{1,3}},
		Effect={2},
		Default=0,
	},
	[39] = { 
		ID=39,
		Name="金刚石(命中)",
		Type=3,
		ConditionType=8,
		Condition={{1,1},{1,2},{1,3}},
		Effect={2},
		Default=0,
	},
	[40] = { 
		ID=40,
		Name="金刚石(气功)",
		Type=3,
		ConditionType=8,
		Condition={{1,1},{1,2},{1,3}},
		Effect={2},
		Default=0,
	},
	[31] = { 
		ID=31,
		Name="寒玉石(防御)",
		Type=4,
		ConditionType=8,
		Condition={{1,1},{1,2},{1,3}},
		Effect={2},
		Default=0,
	},
	[32] = { 
		ID=32,
		Name="寒玉石(武防)",
		Type=4,
		ConditionType=8,
		Condition={{1,1},{1,2},{1,3}},
		Effect={2},
		Default=0,
	},
	[33] = { 
		ID=33,
		Name="寒玉石(生命)",
		Type=4,
		ConditionType=8,
		Condition={{1,1},{1,2},{1,3}},
		Effect={2},
		Default=0,
	},
	[34] = { 
		ID=34,
		Name="寒玉石(闪避)",
		Type=4,
		ConditionType=8,
		Condition={{1,1},{1,2},{1,3}},
		Effect={2},
		Default=0,
	},
	[35] = { 
		ID=35,
		Name="寒玉石(内功)",
		Type=4,
		ConditionType=8,
		Condition={{1,1},{1,2},{1,3}},
		Effect={2},
		Default=0,
	},
	[41] = { 
		ID=41,
		Name="热血石（百变神行）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[42] = { 
		ID=42,
		Name="热血石（护身罡气）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[43] = { 
		ID=43,
		Name="热血石（移花接木）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[44] = { 
		ID=44,
		Name="热血石（回柳身法）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[45] = { 
		ID=45,
		Name="热血石（怒海狂澜）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[46] = { 
		ID=46,
		Name="热血石（冲冠一怒）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[47] = { 
		ID=47,
		Name="热血石（摄魂一击）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[48] = { 
		ID=48,
		Name="热血石（四两千金）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[49] = { 
		ID=49,
		Name="热血石（霸气破甲）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[50] = { 
		ID=50,
		Name="热血石（真武绝击）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[51] = { 
		ID=51,
		Name="热血石（暗影绝杀）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[52] = { 
		ID=52,
		Name="热血石（稳如泰山）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[53] = { 
		ID=53,
		Name="热血石（金钟罡气）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[54] = { 
		ID=54,
		Name="热血石（运气疗伤）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[55] = { 
		ID=55,
		Name="热血石（横练太保）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[56] = { 
		ID=56,
		Name="热血石（乾坤挪移）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[57] = { 
		ID=57,
		Name="热血石（狂神降世）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[58] = { 
		ID=58,
		Name="热血石（转攻为守）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[59] = { 
		ID=59,
		Name="热血石（百步穿杨）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[60] = { 
		ID=60,
		Name="热血石（猎鹰之眼）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[61] = { 
		ID=61,
		Name="热血石（正本培源）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[62] = { 
		ID=62,
		Name="热血石（心神凝聚）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[63] = { 
		ID=63,
		Name="热血石（流星三矢）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[64] = { 
		ID=64,
		Name="热血石（运气行心）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[65] = { 
		ID=65,
		Name="热血石（太极心法）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[66] = { 
		ID=66,
		Name="热血石（体血倍增）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[67] = { 
		ID=67,
		Name="热血石（洗髓易筋）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[68] = { 
		ID=68,
		Name="热血石（妙手回春）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[69] = { 
		ID=69,
		Name="热血石（长功击力）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[70] = { 
		ID=70,
		Name="热血石（吸星大法）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[71] = { 
		ID=71,
		Name="热血石（神佑之气）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[72] = { 
		ID=72,
		Name="热血石（九天真气）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[73] = { 
		ID=73,
		Name="热血石（狂风万破）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[74] = { 
		ID=74,
		Name="热血石（连环飞舞）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[75] = { 
		ID=75,
		Name="热血石（货币增加10%）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[76] = { 
		ID=76,
		Name="热血石（经验增加5%）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[77] = { 
		ID=77,
		Name="热血石（历练增加5%）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[78] = { 
		ID=78,
		Name="热血石（合成概率增加1%）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[79] = { 
		ID=79,
		Name="热血石（气功等级加1）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[80] = { 
		ID=80,
		Name="热血石（灵甲护身）",
		Type=5,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[81] = { 
		ID=81,
		Name="混元金刚石（攻击）",
		Type=6,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[82] = { 
		ID=82,
		Name="混元金刚石（追伤）",
		Type=6,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[83] = { 
		ID=83,
		Name="混元金刚石（武功）",
		Type=6,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[84] = { 
		ID=84,
		Name="混元金刚石（气功）",
		Type=6,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[85] = { 
		ID=85,
		Name="混元金刚石（命中）",
		Type=6,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[86] = { 
		ID=86,
		Name="冰魄寒玉石（防御）",
		Type=7,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[87] = { 
		ID=87,
		Name="冰魄寒玉石（武防）",
		Type=7,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[88] = { 
		ID=88,
		Name="冰魄寒玉石（生命）",
		Type=7,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[89] = { 
		ID=89,
		Name="冰魄寒玉石（闪避）",
		Type=7,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
	[90] = { 
		ID=90,
		Name="冰魄寒玉石（内功）",
		Type=7,
		ConditionType=8,
		Effect={2},
		Default=0,
	},
}
return config
