local config = { 
	[1] = { 
		ID=1,
		Name="sWearNotOfWoMan",
		DetailStr="非女性用品.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[2] = { 
		ID=2,
		Name="sWearNotOfMan",
		DetailStr="非男性用品.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[3] = { 
		ID=3,
		Name="sRankLevelName",
		DetailStr="%s\\Level",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[4] = { 
		ID=4,
		Name="sManDearName",
		DetailStr="{0}的老公",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[5] = { 
		ID=5,
		Name="sWoManDearName",
		DetailStr="{0}的老婆",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[6] = { 
		ID=6,
		Name="sMasterName",
		DetailStr="{0}的师父",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[7] = { 
		ID=7,
		Name="sNoMasterName",
		DetailStr="{0}的徒弟",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[8] = { 
		ID=8,
		Name="sBrotherName",
		DetailStr="{0}的兄弟",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[9] = { 
		ID=9,
		Name="sSistersName",
		DetailStr="{0}的姐妹",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[10] = { 
		ID=10,
		Name="sHumanShowName",
		DetailStr="{0}\\{1}\\{2}\\{3}\\{4}\\{5}\\",
		Desc="角色名，国家名，行会名，道侣名，师父名，结拜兄弟名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[11] = { 
		ID=11,
		Name="sCanotTakeOffItem",
		DetailStr="无法取下物品.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[12] = { 
		ID=12,
		Name="sCanotGetItems",
		DetailStr="无法携带更多的东西.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[13] = { 
		ID=13,
		Name="sCanotTryDealMsg",
		DetailStr="当前无法进行此操作！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[14] = { 
		ID=14,
		Name="sDisableDealItemsMsg",
		DetailStr="交易功能暂时关闭！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[15] = { 
		ID=15,
		Name="sPleaseTryDealLaterMsg",
		DetailStr="请稍候再交易！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[16] = { 
		ID=16,
		Name="sOpenedDealMsg",
		DetailStr="开始交易.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[17] = { 
		ID=17,
		Name="sDealActionCancelMsg",
		DetailStr="交易取消！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[18] = { 
		ID=18,
		Name="sPoseDisableDealMsg",
		DetailStr="对方禁止进入交易...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[19] = { 
		ID=19,
		Name="sDealSuccessMsg",
		DetailStr="交易成功...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[20] = { 
		ID=20,
		Name="sDealOKTooFast",
		DetailStr="过早按了成交按钮。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[21] = { 
		ID=21,
		Name="sYourBagSizeTooSmall",
		DetailStr="你的背包空间不够，无法装下对方交易给你的物品！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[22] = { 
		ID=22,
		Name="sDealHumanBagSizeTooSmall",
		DetailStr="交易对方的背包空间不够，无法装下对方交易给你的物品！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[23] = { 
		ID=23,
		Name="sYourGoldLargeThenLimit",
		DetailStr="你的所带的金币太多，无法装下对方交易给你的金币！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[24] = { 
		ID=24,
		Name="sDealHumanGoldLargeThenLimit",
		DetailStr="交易对方的所带的金币太多，无法装下对方交易给你的金币！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[25] = { 
		ID=25,
		Name="sYouDealOKMsg",
		DetailStr="你已经确认交易了.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[26] = { 
		ID=26,
		Name="sPoseDealOKMsg",
		DetailStr="对方已经确认交易了.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[27] = { 
		ID=27,
		Name="sCanotUseDrugOnThisMap",
		DetailStr="此地图不允许使用任何药品.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[28] = { 
		ID=28,
		Name="sCanotUseItemMsg",
		DetailStr="当前无法进行此操作！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[29] = { 
		ID=29,
		Name="sYouPoisoned",
		DetailStr="你中毒了[时间:{0}秒，点数:{1}点].",
		Desc="点数，时长",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[30] = { 
		ID=30,
		Name="sCanotDropInSafeZoneMsg",
		DetailStr="安全区不允许扔东西在地上！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[31] = { 
		ID=31,
		Name="sCanotPickUpItem",
		DetailStr="在一定时间以内无法捡起此物品！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[32] = { 
		ID=32,
		Name="sCanotDropGoldMsg",
		DetailStr="太少的金币不允许扔在地上！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[33] = { 
		ID=33,
		Name="sWeaptonMakeLuck",
		DetailStr="武器被加幸运了...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[34] = { 
		ID=34,
		Name="sWeaptonNotMakeLuck",
		DetailStr="无效.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[35] = { 
		ID=35,
		Name="sTheWeaponIsCursed",
		DetailStr="你的武器被诅咒了.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[36] = { 
		ID=36,
		Name="sWeaponRepairSuccess",
		DetailStr="武器修复成功...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[37] = { 
		ID=37,
		Name="sYouMurderedMsg",
		DetailStr="你犯了谋杀罪...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[38] = { 
		ID=38,
		Name="sYouKilledByMsg",
		DetailStr="你被{0}杀害了...",
		Desc="杀人者名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[39] = { 
		ID=39,
		Name="sYouProtectedByLawOfDefense",
		DetailStr="[--你受到正当规则保护--]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[40] = { 
		ID=40,
		Name="sEnableAuthAllyGuild",
		DetailStr="[允许门派联盟]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[41] = { 
		ID=41,
		Name="sDisableAuthAllyGuild",
		DetailStr="[禁止门派联盟]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[42] = { 
		ID=42,
		Name="sfUnMarryManLoginMsg",
		DetailStr="你的老婆{0}已经强行与你脱离了夫妻关系了！！！",
		Desc="道侣名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[43] = { 
		ID=43,
		Name="sfUnMarryWoManLoginMsg",
		DetailStr="你的老公{0}已经强行与你脱离了夫妻关系了！！！",
		Desc="道侣名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[44] = { 
		ID=44,
		Name="sManLoginDearOnlineSelfMsg",
		DetailStr="你的老婆{0}当前位于{1}({2}:{3}).",
		Desc="道侣名，地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[45] = { 
		ID=45,
		Name="sManLoginDearOnlineDearMsg",
		DetailStr="你的老公{0}在:{1}({2}:{3})上线了.",
		Desc="道侣名，地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[46] = { 
		ID=46,
		Name="sWoManLoginDearOnlineSelfMsg",
		DetailStr="你的老公当前位于{0}({1}:{2}).",
		Desc="地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[47] = { 
		ID=47,
		Name="sWoManLoginDearOnlineDearMsg",
		DetailStr="你的老婆{0}在:{1}({2}:{3}) 上线了.",
		Desc="道侣名，地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[48] = { 
		ID=48,
		Name="sManLoginDearNotOnlineMsg",
		DetailStr="你的老婆现在不在线.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[49] = { 
		ID=49,
		Name="sWoManLoginDearNotOnlineMsg",
		DetailStr="你的老公现在不在线.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[50] = { 
		ID=50,
		Name="sYouAreNotMarryedMsg",
		DetailStr="你都没结婚查什么？",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[51] = { 
		ID=51,
		Name="sYourWifeNotOnlineMsg",
		DetailStr="你的老婆还没有上线！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[52] = { 
		ID=52,
		Name="sYourHusbandNotOnlineMsg",
		DetailStr="你的老公还没有上线！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[53] = { 
		ID=53,
		Name="sYourWifeNowLocateMsg",
		DetailStr="你的老婆现在位于:",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[54] = { 
		ID=54,
		Name="sYourHusbandSearchLocateMsg",
		DetailStr="你的老公正在找你，他现在位于:",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[55] = { 
		ID=55,
		Name="sYourHusbandNowLocateMsg",
		DetailStr="你的老公现在位于:",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[56] = { 
		ID=56,
		Name="sYourWifeSearchLocateMsg",
		DetailStr="你的老婆正在找你，他现在位于:",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[57] = { 
		ID=57,
		Name="sAttackModeOfAll",
		DetailStr="[攻击模式: 全体攻击]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[58] = { 
		ID=58,
		Name="sAttackModeOfPeaceful",
		DetailStr="[攻击模式: 和平攻击]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[59] = { 
		ID=59,
		Name="sAttackModeOfDear",
		DetailStr="[攻击模式: 夫妻攻击]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[60] = { 
		ID=60,
		Name="sAttackModeOfMaster",
		DetailStr="[攻击模式: 师徒攻击]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[61] = { 
		ID=61,
		Name="sAttackModeOfGroup",
		DetailStr="[攻击模式: 编组攻击]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[62] = { 
		ID=62,
		Name="sAttackModeOfGuild",
		DetailStr="[攻击模式: 门派攻击]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[63] = { 
		ID=63,
		Name="sAttackModeOfRedWhite",
		DetailStr="[攻击模式: 红名攻击]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[64] = { 
		ID=64,
		Name="sAttackModeOfCountry",
		DetailStr="[攻击模式: 国家攻击]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[65] = { 
		ID=65,
		Name="sAttackModeOfCAMPPK",
		DetailStr="[攻击模式: 阵营模式]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[66] = { 
		ID=66,
		Name="sAttackModeOfSERVERPK",
		DetailStr="[攻击模式: 区服模式]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[67] = { 
		ID=67,
		Name="sGameMasterMode",
		DetailStr="已进入管理员模式.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[68] = { 
		ID=68,
		Name="sReleaseGameMasterMode",
		DetailStr="已退出管理员模式.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[69] = { 
		ID=69,
		Name="sObserverMode",
		DetailStr="已进入隐身模式.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[70] = { 
		ID=70,
		Name="sReleaseObserverMode",
		DetailStr="已退出隐身模式.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[71] = { 
		ID=71,
		Name="sSupermanMode",
		DetailStr="已进入无敌模式.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[72] = { 
		ID=72,
		Name="sReleaseSupermanMode",
		DetailStr="已退出无敌模式.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[73] = { 
		ID=73,
		Name="sNowCurrDateTime",
		DetailStr="前系统日期时间: {0}",
		Desc="时间字符串",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[74] = { 
		ID=74,
		Name="sEnableHearWhisper",
		DetailStr="[允许私聊]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[75] = { 
		ID=75,
		Name="sDisableHearWhisper",
		DetailStr="[禁止私聊]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[76] = { 
		ID=76,
		Name="sEnableShoutMsg",
		DetailStr="[允许群聊]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[77] = { 
		ID=77,
		Name="sDisableShoutMsg",
		DetailStr="[禁止群聊]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[78] = { 
		ID=78,
		Name="sEnableDealMsg",
		DetailStr="[允许交易]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[79] = { 
		ID=79,
		Name="sDisableDealMsg",
		DetailStr="[禁止交易]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[80] = { 
		ID=80,
		Name="sEnableGuildChat",
		DetailStr="[允许门派聊天]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[81] = { 
		ID=81,
		Name="sDisableGuildChat",
		DetailStr="[禁止门派聊天]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[82] = { 
		ID=82,
		Name="sEnableJoinGuild",
		DetailStr="[允许加入门派]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[83] = { 
		ID=83,
		Name="sDisableJoinGuild",
		DetailStr="[禁止加入门派]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[84] = { 
		ID=84,
		Name="sGameCommandPrvMsgUnLimitMsg",
		DetailStr="{0} 已从禁止私聊列表中删除...",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[85] = { 
		ID=85,
		Name="sGameCommandPrvMsgLimitMsg",
		DetailStr="{0} 已被加入禁止私聊列表...",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[86] = { 
		ID=86,
		Name="sEnableDearRecall",
		DetailStr="[允许夫妻传送]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[87] = { 
		ID=87,
		Name="sDisableDearRecall",
		DetailStr="[禁止夫妻传送]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[88] = { 
		ID=88,
		Name="sEnableMasterRecall",
		DetailStr="[允许师徒传送]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[89] = { 
		ID=89,
		Name="sDisableMasterRecall",
		DetailStr="[禁止师徒传送]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[90] = { 
		ID=90,
		Name="sfUnMasterLoginMsg",
		DetailStr="你的一个徒弟已经背判师门了！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[91] = { 
		ID=91,
		Name="sfUnMasterListLoginMsg",
		DetailStr="你的师父{0}已经将你逐出师门了！！！",
		Desc="师父名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[92] = { 
		ID=92,
		Name="sMasterListOnlineSelfMsg",
		DetailStr="你的师父{0}当前位于{1}({2}:{3})。",
		Desc="师父名，地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[93] = { 
		ID=93,
		Name="sMasterListOnlineMasterMsg",
		DetailStr="你的徒弟{0}在:{1}({2}:{3})上线了！！！。",
		Desc="徒弟名，地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[94] = { 
		ID=94,
		Name="sMasterOnlineSelfMsg",
		DetailStr="你的徒弟当前位于{0}({1}:{2})。",
		Desc="地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[95] = { 
		ID=95,
		Name="sMasterOnlineMasterListMsg",
		DetailStr="你的师父{0}在:{1}({2}:{3}) 上线了！！！。",
		Desc="师父名，地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[96] = { 
		ID=96,
		Name="sMasterListNotOnlineMsg",
		DetailStr="你的师父现不在线！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[97] = { 
		ID=97,
		Name="sMasterNotOnlineMsg",
		DetailStr="你的徒弟现不在线！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[98] = { 
		ID=98,
		Name="sYouAreNotMasterMsg",
		DetailStr="你都没师徒关系查什么？",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[99] = { 
		ID=99,
		Name="sYourMasterNotOnlineMsg",
		DetailStr="你的师父还没有上线！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[100] = { 
		ID=100,
		Name="sYourMasterListNotOnlineMsg",
		DetailStr="你的徒弟还没有上线！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[101] = { 
		ID=101,
		Name="sYourMasterNowLocateMsg",
		DetailStr="你的师父现在位于:",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[102] = { 
		ID=102,
		Name="sYourMasterListSearchLocateMsg",
		DetailStr="你的徒弟正在找你，他现在位于:",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[103] = { 
		ID=103,
		Name="sYourMasterListNowLocateMsg",
		DetailStr="你的徒弟现在位于:",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[104] = { 
		ID=104,
		Name="sYourMasterSearchLocateMsg",
		DetailStr="你的师父正在找你，他现在位于:",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[105] = { 
		ID=105,
		Name="sYourMasterListUnMasterOKMsg",
		DetailStr="你的徒弟{0}已经圆满出师了！！！",
		Desc="徒弟名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[106] = { 
		ID=106,
		Name="sYouAreUnMasterOKMsg",
		DetailStr="你已经出师了！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[107] = { 
		ID=107,
		Name="sUnMasterLoginMsg",
		DetailStr="你的一个徒弟已经圆满出师了！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[108] = { 
		ID=108,
		Name="sTotalOnlineCountMsg",
		DetailStr="总在线人数: {0}",
		Desc="数量",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[109] = { 
		ID=109,
		Name="sGameCommandShutupHelpMsg",
		DetailStr="人物名称  时间长度(分钟)",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[110] = { 
		ID=110,
		Name="sGameCommandShutupHumanMsg",
		DetailStr="{0} 已被禁言{1}分钟",
		Desc="角色名，时长分钟",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[111] = { 
		ID=111,
		Name="sGameCommandShutupReleaseHelpMsg",
		DetailStr="人物名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[112] = { 
		ID=112,
		Name="sGameCommandShutupReleaseCanSendMsg",
		DetailStr="你已经恢复聊天功能！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[113] = { 
		ID=113,
		Name="sGameCommandShutupReleaseHumanCanSendMsg",
		DetailStr="{0} 已经恢复聊天。",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[114] = { 
		ID=114,
		Name="sGameCommandShutupListIsNullMsg",
		DetailStr="禁言列表为空！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[115] = { 
		ID=115,
		Name="sYourCharNameDenyLogon",
		DetailStr="你当前登录的人物已被禁止登录了！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[116] = { 
		ID=116,
		Name="sGameCommandHumName",
		DetailStr="人物名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[117] = { 
		ID=117,
		Name="sGameCommandSuperTingHelpMsg",
		DetailStr="人物名称 范围(0-10)",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[118] = { 
		ID=118,
		Name="sGameCommandMapMoveHelpMsg",
		DetailStr="源地图  目标地图",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[119] = { 
		ID=119,
		Name="sGameCommandMapMoveMapNotFound",
		DetailStr="地图{0}不存在！！！",
		Desc="地图名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[120] = { 
		ID=120,
		Name="sGameCommandMapInfoMsg",
		DetailStr="地图名称: {0}({1})",
		Desc="地图ID，地图名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[121] = { 
		ID=121,
		Name="sGameCommandMapInfoSizeMsg",
		DetailStr="地图大小: X({0}) Y({1})",
		Desc="地图X，地图Y",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[122] = { 
		ID=122,
		Name="sGameCommandRecallMobHelpMsg",
		DetailStr="怪物名称 数量 等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[123] = { 
		ID=123,
		Name="sGameCommandMobCountHelpMsg",
		DetailStr="地图号",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[124] = { 
		ID=124,
		Name="sGameCommandMobCountMapNotFound",
		DetailStr="指定的地图不存在！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[125] = { 
		ID=125,
		Name="sGameCommandMobCountMonsterCount",
		DetailStr="怪物数量：{0}",
		Desc="数量",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[126] = { 
		ID=126,
		Name="sGameCommandReAliveMsg",
		DetailStr="{0} 已获重生.",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[127] = { 
		ID=127,
		Name="sGameCommandFreePKHumanMsg",
		DetailStr="你的PK值已经被清除...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[128] = { 
		ID=128,
		Name="sGameCommandFreePKMsg",
		DetailStr="{0}的PK值已经被清除...",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[129] = { 
		ID=129,
		Name="sGameCommandPKPointMsg",
		DetailStr="{0}的PK点数为:{1}",
		Desc="角色名，PK点数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[130] = { 
		ID=130,
		Name="sGameCommandIncPkPointHelpMsg",
		DetailStr="人物名称 PK点数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[131] = { 
		ID=131,
		Name="sGameCommandIncPkPointAddPointMsg",
		DetailStr="{0}的PK值已增加{1}点...",
		Desc="角色名，点数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[132] = { 
		ID=132,
		Name="sGameCommandIncPkPointDecPointMsg",
		DetailStr="{0}的PK值已减少{1}点...",
		Desc="角色名，点数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[133] = { 
		ID=133,
		Name="sGameCommandChangeJobHelpMsg",
		DetailStr="人物名称 职业类型(Warrior Wizard Taoist)",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[134] = { 
		ID=134,
		Name="sGameCommandChangeJobMsg",
		DetailStr="{0} 的职业更改成功。",
		Desc="角色名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[135] = { 
		ID=135,
		Name="sGameCommandChangeJobHumanMsg",
		DetailStr="职业更改成功。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[136] = { 
		ID=136,
		Name="sGameCommandSbkGoldHelpMsg",
		DetailStr="城堡名称 控制符(=、-、+) 金币数(1-100000000)",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[137] = { 
		ID=137,
		Name="sGameCommandSbkGoldCastleNotFoundMsg",
		DetailStr="城堡{0}未找到！！！",
		Desc="沙巴克城名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[138] = { 
		ID=138,
		Name="sGameCommandSbkGoldShowMsg",
		DetailStr="{0}的金币数为: {1} 今天收入: {2}",
		Desc="沙巴克城名，累计金币数，当日收入",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[139] = { 
		ID=139,
		Name="sGameCommandReloadLineNoticeSuccessMsg",
		DetailStr="重新加载公告设置信息完成。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[140] = { 
		ID=140,
		Name="sGameCommandReloadLineNoticeFailMsg",
		DetailStr="重新加载公告设置信息失败！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[141] = { 
		ID=141,
		Name="sGameCommandReloadNoticeSuccessMsg",
		DetailStr="重新加载欢迎公告信息完成。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[142] = { 
		ID=142,
		Name="sGameCommandReloadNoticeFailMsg",
		DetailStr="重新加载欢迎公告信息失败！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[143] = { 
		ID=143,
		Name="sGameCommandReloadGuildHelpMsg",
		DetailStr="门派名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[144] = { 
		ID=144,
		Name="sGameCommandReloadGuildOnMasterserver",
		DetailStr="此命令只能在主游戏服务器上执行！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[145] = { 
		ID=145,
		Name="sGameCommandReloadGuildNotFoundGuildMsg",
		DetailStr="未找到门派{0}！！！",
		Desc="行会名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[146] = { 
		ID=146,
		Name="sGameCommandReloadGuildSuccessMsg",
		DetailStr="门派{0}重加载成功...",
		Desc="行会名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[147] = { 
		ID=147,
		Name="sKickClientUserMsg",
		DetailStr="请不要使用非法外挂软件.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[148] = { 
		ID=148,
		Name="sPetRest",
		DetailStr="下属：休息",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[149] = { 
		ID=149,
		Name="sPetAttack",
		DetailStr="下属：攻击",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[150] = { 
		ID=150,
		Name="sPetDefend",
		DetailStr="下属：守护",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[151] = { 
		ID=151,
		Name="sYouFoundNothing",
		DetailStr="未获取任何物品...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[152] = { 
		ID=152,
		Name="sGameCommandMobFireBurnHelpMsg",
		DetailStr="命令格式: {0} {1} {2} {3} {4} {5} {6}",
		Desc="命令，参数1，参数2，参数3，参数4，参数5，参数6",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[153] = { 
		ID=153,
		Name="sGameCommandMobFireBurnMapNotFountMsg",
		DetailStr="地图{0} 不存在",
		Desc="地图名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[154] = { 
		ID=154,
		Name="sOffLineReLogin",
		DetailStr="由于网络不稳定你已经掉线，请重新登录！！！{0}",
		Desc="服务器区服ID",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[155] = { 
		ID=155,
		Name="sExpRateRestore",
		DetailStr="经验倍数恢复正常...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[156] = { 
		ID=156,
		Name="sDCRateRestore",
		DetailStr="攻击力倍数恢复正常...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[157] = { 
		ID=157,
		Name="sReliveBuffOff",
		DetailStr="你的复活BUFF消失了。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[158] = { 
		ID=158,
		Name="sDisableSkillInThisMap",
		DetailStr="当前地图禁止使用技能{0}",
		Desc="技能名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[159] = { 
		ID=159,
		Name="sJoinGuild",
		DetailStr="你已加入门派: {0}",
		Desc="行会名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[160] = { 
		ID=160,
		Name="sRecallFail",
		DetailStr="召唤失败！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[161] = { 
		ID=161,
		Name="sRecharge",
		DetailStr="充值 {0}",
		Desc="货币数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[162] = { 
		ID=162,
		Name="sRechargeCashBack",
		DetailStr="充值返现 {0}",
		Desc="返现货币数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[163] = { 
		ID=163,
		Name="sNeedLevel",
		DetailStr="需要等级：{0}",
		Desc="等级数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[164] = { 
		ID=164,
		Name="sNeedMaxDC",
		DetailStr="需要攻击力：{0}",
		Desc="攻击上限",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[165] = { 
		ID=165,
		Name="sNeedMaxMC",
		DetailStr="需要魔法力：{0}",
		Desc="魔法攻击力上限",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[166] = { 
		ID=166,
		Name="sNeedMaxSC",
		DetailStr="需要精神力：{0}",
		Desc="道术上限",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[167] = { 
		ID=167,
		Name="sNeedReLevel",
		DetailStr="需要转职等级：{0}",
		Desc="转职等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[168] = { 
		ID=168,
		Name="sNeedReputation",
		DetailStr="需要声望点：{0}",
		Desc="声望点数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[169] = { 
		ID=169,
		Name="sJobErrOrNeedLevel",
		DetailStr="职业不对或等级不够",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[170] = { 
		ID=170,
		Name="sJobErrOrNeedDC",
		DetailStr="职业不对或攻击力不够",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[171] = { 
		ID=171,
		Name="sJobErrOrNeedMC",
		DetailStr="职业不对或魔法力不够",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[172] = { 
		ID=172,
		Name="sJobErrOrNeedSC",
		DetailStr="职业不对或精神力不够",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[173] = { 
		ID=173,
		Name="sLevelEqual",
		DetailStr="等级必须为{0}",
		Desc="等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[174] = { 
		ID=174,
		Name="sNeedReLevelOrLevel",
		DetailStr="转职等级或等级不够",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[175] = { 
		ID=175,
		Name="sNeedReLevelOrDC",
		DetailStr="转职等级或攻击力不够",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[176] = { 
		ID=176,
		Name="sNeedReLevelOrMC",
		DetailStr="转职等级或魔法力不够",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[177] = { 
		ID=177,
		Name="sNeedReLevelOrSC",
		DetailStr="转职等级或精神力不够",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[178] = { 
		ID=178,
		Name="sNeedReLevlOrReputation",
		DetailStr="转职等级或声望不够",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[179] = { 
		ID=179,
		Name="sNeedReLevlOrJobErr",
		DetailStr="转职等级或职业不匹配",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[180] = { 
		ID=180,
		Name="sNeedGuildMember",
		DetailStr="门派成员专用",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[181] = { 
		ID=181,
		Name="sNeedGuildMaster",
		DetailStr="门派掌门专用",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[182] = { 
		ID=182,
		Name="sCanotUseItemInDeal",
		DetailStr="此物品禁止在交易状态使用！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[183] = { 
		ID=183,
		Name="sAttackSpeedAdd",
		DetailStr="攻击速度增加{0}秒",
		Desc="时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[184] = { 
		ID=184,
		Name="sUseInFuture",
		DetailStr="请稍后再使用此功能",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[185] = { 
		ID=185,
		Name="sNoUse",
		DetailStr="无效",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[186] = { 
		ID=186,
		Name="sCanotUseInArea",
		DetailStr="此处无法使用",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[187] = { 
		ID=187,
		Name="sAllEquipRepairPoint",
		DetailStr="[全身装备持久已经修复完毕:共修复{0}点]",
		Desc="点数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[188] = { 
		ID=188,
		Name="sAllEquipRepairOK",
		DetailStr="[全身装备持久已经修复完毕]",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[189] = { 
		ID=189,
		Name="sNoEnoughLevel",
		DetailStr="等级不足！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[190] = { 
		ID=190,
		Name="sNotForYourRole",
		DetailStr="不适合你的角色学习！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[191] = { 
		ID=191,
		Name="sForbidCharForInput",
		DetailStr="禁止输入 @$<>/\\ 字符",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[192] = { 
		ID=192,
		Name="sForbidSellItem",
		DetailStr="此物品禁止出售！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[193] = { 
		ID=193,
		Name="sForbidRepairItem",
		DetailStr="此物品禁止修理！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[194] = { 
		ID=194,
		Name="sCanotGetMailItemWhenBagFull",
		DetailStr="背包满不能取出邮件物品！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[195] = { 
		ID=195,
		Name="sCanotJoinGroupWhenDeath",
		DetailStr="死亡状态不允许组队！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[196] = { 
		ID=196,
		Name="sItemForbidThrow",
		DetailStr="此物品禁止丢弃！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[197] = { 
		ID=197,
		Name="sItemForbidThrowInMap",
		DetailStr="此地图禁止丢弃物品 {0}",
		Desc="物品名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[198] = { 
		ID=198,
		Name="sBuyFailWhenBagFull",
		DetailStr="背包已满，购买失败！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[199] = { 
		ID=199,
		Name="sOnlyOwnerCanPick",
		DetailStr="此物品仅归属者可拾取",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[200] = { 
		ID=200,
		Name="sOnlyBossRecallerCanPick",
		DetailStr="此物品仅BOSS召唤者可拾取",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[201] = { 
		ID=201,
		Name="sCanotSplitWhenBagFull",
		DetailStr="背包已满，无法拆分！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[202] = { 
		ID=202,
		Name="sMemberNotExist",
		DetailStr="成员不存在请重试！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[203] = { 
		ID=203,
		Name="sWaitForDataLoading",
		DetailStr="数据加载中...稍后再操作",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[204] = { 
		ID=204,
		Name="sItemForbidSaveToStorage",
		DetailStr="此物品禁止存仓库！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[205] = { 
		ID=205,
		Name="sCanotDeposit",
		DetailStr="您不能寄存物品。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[206] = { 
		ID=206,
		Name="sCanotDealInMap",
		DetailStr="当前地图禁止交易！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[207] = { 
		ID=207,
		Name="sCanotDoWhenBagFull",
		DetailStr="背包已满，无法操作！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[208] = { 
		ID=208,
		Name="sCanotChangeAtkModeInMap",
		DetailStr="当前地图禁止切换攻击模式！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[209] = { 
		ID=209,
		Name="sCanotChangeAtkModeInSecond",
		DetailStr="{0}秒内，禁止切换攻击模式！",
		Desc="时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[210] = { 
		ID=210,
		Name="sPressLockFirst",
		DetailStr="请先点击锁定按钮。'",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[211] = { 
		ID=211,
		Name="sTraderNoEnoughMoneyForDeal",
		DetailStr="对方没有足够的货币交易",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[212] = { 
		ID=212,
		Name="sNoEnoughMoneyForDeal",
		DetailStr="你没有足够的货币交易",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[213] = { 
		ID=213,
		Name="sItemForbidInMap",
		DetailStr="当前地图禁止使用物品{0}",
		Desc="物品名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[214] = { 
		ID=214,
		Name="sItemForbidForPlayer",
		DetailStr="“{0}”禁止人物使用！！！",
		Desc="物品名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[215] = { 
		ID=215,
		Name="sNoEnoughMoney",
		DetailStr="货币不足！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[216] = { 
		ID=216,
		Name="sCanGetExpWhenHighLevel",
		DetailStr="您的等级已经超过{0}级，无法释放{1}的经验值！",
		Desc="等级，物品名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[217] = { 
		ID=217,
		Name="sForceOfflineForMinority",
		DetailStr="由于你未实名认证或未成年，你已被强行离线！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[218] = { 
		ID=218,
		Name="sCanotStorageInMap",
		DetailStr="此地图禁止存取仓库！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[219] = { 
		ID=219,
		Name="sForbidDataChange",
		DetailStr="非法数据调整！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[220] = { 
		ID=220,
		Name="sErrDataChange",
		DetailStr="非有效数据调整！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[221] = { 
		ID=221,
		Name="sBeRelived",
		DetailStr="你已被复活 剩余复活次数{0}次",
		Desc="次数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[222] = { 
		ID=222,
		Name="sCanotTakeMoreItem",
		DetailStr="背包已经满，无法携带更多东西！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[223] = { 
		ID=223,
		Name="sYouCanotTakeMoreItem",
		DetailStr="你的背包无法携带更多的物品！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[224] = { 
		ID=224,
		Name="sOnlyGuildMasterCanDo",
		DetailStr="只有门派掌门人才能申请！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[225] = { 
		ID=225,
		Name="sCmdCanotRunInServer",
		DetailStr="这个命令不能在本服务器上使用！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[226] = { 
		ID=226,
		Name="sGuildNotExist",
		DetailStr="门派不存在！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[227] = { 
		ID=227,
		Name="sCanotRideInMap",
		DetailStr="当前地图禁止骑马",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[228] = { 
		ID=228,
		Name="sForceOfflineForCertFail",
		DetailStr="与服务器认证失败，已被强制离线！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[229] = { 
		ID=229,
		Name="sForbiddenAccountOrRole",
		DetailStr="您的账号或角色已被服务器封禁！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[230] = { 
		ID=230,
		Name="sCanotDoBySelf",
		DetailStr="不能与自己操作！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[231] = { 
		ID=231,
		Name="sSomeoneOffLine",
		DetailStr="对方已离线！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[232] = { 
		ID=232,
		Name="sYouTwoNotInOneMap",
		DetailStr="双方必须在同一地图才可以申请！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[233] = { 
		ID=233,
		Name="sTakeOffFailWhenBagFull",
		DetailStr="背包已满，脱装失败！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[234] = { 
		ID=234,
		Name="sHireOK",
		DetailStr="雇佣成功.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[235] = { 
		ID=235,
		Name="sCanotHireNow",
		DetailStr="现在无法雇佣！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[236] = { 
		ID=236,
		Name="sHiredBefore",
		DetailStr="早已雇佣！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[237] = { 
		ID=237,
		Name="sErrCmd",
		DetailStr="指令错误！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[238] = { 
		ID=238,
		Name="sNotEnoughMoneyInCastle",
		DetailStr="城内资金不足！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[239] = { 
		ID=239,
		Name="sItemDBReloadOK",
		DetailStr="物品数据库重新加载完成。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[240] = { 
		ID=240,
		Name="sSKillDBReloadOK",
		DetailStr="魔法数据库重新加载完成。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[241] = { 
		ID=241,
		Name="sMonDBReloadOK",
		DetailStr="怪物数据库重新加载完成。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[242] = { 
		ID=242,
		Name="sMiniMapReloadOK",
		DetailStr="小地图配置重新加载完成。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[243] = { 
		ID=243,
		Name="sCanDoWhenHighLevel",
		DetailStr="你的等级要在{0}级以上才能用此功能！！！",
		Desc="等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[244] = { 
		ID=244,
		Name="sDropItemHint",
		DetailStr="{0}在地图{1}中掉落{2}，坐标({2},{3})",
		Desc="怪物名，地图名，掉落物品名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[245] = { 
		ID=245,
		Name="sNoAmulet",
		DetailStr="包裹或身上没有护身符！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[246] = { 
		ID=246,
		Name="sNoPoison",
		DetailStr="包裹或身上没有毒药！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[247] = { 
		ID=247,
		Name="sNoGrayPowder",
		DetailStr="包裹或身上没有灰色药粉！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[248] = { 
		ID=248,
		Name="sNoYellowPowder",
		DetailStr="包裹或身上没有黄色药粉！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[249] = { 
		ID=249,
		Name="sFrosted",
		DetailStr="你被冰冻了，持续{0}秒",
		Desc="时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[250] = { 
		ID=250,
		Name="sNetBlocked",
		DetailStr="你被网住了，持续{0}秒",
		Desc="时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[251] = { 
		ID=251,
		Name="sParalysis",
		DetailStr="你被麻痹了，持续{0}秒",
		Desc="时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[252] = { 
		ID=252,
		Name="sGreenPoison",
		DetailStr="你中了绿毒了，持续{0}秒，点数：{1}",
		Desc="时长秒，点数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[253] = { 
		ID=253,
		Name="sRedPoison",
		DetailStr="你中了红毒了，持续%d秒",
		Desc="时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[254] = { 
		ID=254,
		Name="sSpeedAbnormal",
		DetailStr="速度异常 Ident: {0} Time: {1}",
		Desc="消息ID，时长",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[255] = { 
		ID=255,
		Name="sTrainSkillLevel",
		DetailStr="{0}的修改炼等级为{1}",
		Desc="技能名称，等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[256] = { 
		ID=256,
		Name="sPlayerTrainSkillLevel",
		DetailStr="{0}的技能{1}修炼等级为{2}",
		Desc="玩家名，技能名称，等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[257] = { 
		ID=257,
		Name="sSkillDel",
		DetailStr="技能{0}已删除。",
		Desc="技能名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[258] = { 
		ID=258,
		Name="sPlayerSkillDel",
		DetailStr="{0}的技能{1]已删除。",
		Desc="玩家名，技能名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[259] = { 
		ID=259,
		Name="sTrainSkillOK",
		DetailStr="{0}技能修炼成功！！！",
		Desc="技能名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[260] = { 
		ID=260,
		Name="sItemNotForStall",
		DetailStr="{0} 此物品禁止摆摊!",
		Desc="物品名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[261] = { 
		ID=261,
		Name="sWaitForJoinAfterLeaveGuild",
		DetailStr="退出门派后，需要{0}分钟后才能再次进入门派!",
		Desc="时长分钟",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[262] = { 
		ID=262,
		Name="sCanotJoinGuildWhenCastleWar",
		DetailStr="攻城战期间无法加入门派！!",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[263] = { 
		ID=263,
		Name="sAppointGuildRankFail",
		DetailStr="任命失败，最多任命{0}名{1}！!",
		Desc="数量，行会等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[264] = { 
		ID=264,
		Name="sDealRefused",
		DetailStr="{0}拒绝了你的交易！",
		Desc="对方玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[265] = { 
		ID=265,
		Name="sItemNotForAuction",
		DetailStr="{0} 此物品禁止拍卖！",
		Desc="物品名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[266] = { 
		ID=266,
		Name="sItemCountNotEnough",
		DetailStr="{0}不足{1}个！",
		Desc="物品名，数量",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[267] = { 
		ID=267,
		Name="sOfflineTime",
		DetailStr="离线时间：{0} 分钟",
		Desc="时长分钟",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[268] = { 
		ID=268,
		Name="sRoleForbidInServer",
		DetailStr="您的[{0}]已被服务器封禁！！",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[269] = { 
		ID=269,
		Name="sRoleForbidTimeInServer",
		DetailStr="由于您的[{0}]已被服务器封禁，您当前无法进入游戏！！！<br> 封禁截止时间[{1}]",
		Desc="玩家名，封禁截止时间",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[270] = { 
		ID=270,
		Name="sCanotSayTime",
		DetailStr="【系统】你不允许发言！ 剩余时间 {0} 秒!",
		Desc="时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[271] = { 
		ID=271,
		Name="sItemExpFull",
		DetailStr="{0} 的经验已聚满！！！",
		Desc="物品名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[272] = { 
		ID=272,
		Name="sItemNotForLeftBracelet",
		DetailStr="“{0}”禁止携带在人物左手镯位置！！！",
		Desc="物品名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[273] = { 
		ID=273,
		Name="sPlayerOffline",
		DetailStr="{0} 不在线！",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[274] = { 
		ID=274,
		Name="sMarrayByFemale",
		DetailStr="你求婚的对象只能是女性！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[275] = { 
		ID=275,
		Name="sSwornBySameGender",
		DetailStr="结拜邀请双方性别一致！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[276] = { 
		ID=276,
		Name="sForceDivorceBySomeOne",
		DetailStr="{0} 已经强行与你离婚！！！",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[277] = { 
		ID=277,
		Name="sForceDivorce",
		DetailStr="你与 {0} 已经强行离婚成功！！！",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[278] = { 
		ID=278,
		Name="sCanotDivorceWhenOffline",
		DetailStr="{0} 不在线无法申请离婚！",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[279] = { 
		ID=279,
		Name="sRunTime",
		DetailStr="执行标签：{0}  耗时： {1} 微秒",
		Desc="标签名，时长微秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[280] = { 
		ID=280,
		Name="sNotMarried",
		DetailStr="你还没有结婚！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[281] = { 
		ID=281,
		Name="sCanotSayOfLevel",
		DetailStr="等级必须大于 {0} 级才可以说话",
		Desc="等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[282] = { 
		ID=282,
		Name="sShoutWaitTime",
		DetailStr="提示：请在{0}秒后使用喊话",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[283] = { 
		ID=283,
		Name="sOnlyMasterCanDo",
		DetailStr="只能师父才能使用此功能！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[284] = { 
		ID=284,
		Name="sNoPupilOnline",
		DetailStr="你的徒弟一个都不在线！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[285] = { 
		ID=285,
		Name="sCanotTransmitOfMasterPupil",
		DetailStr="本地图禁止师徒传送！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[286] = { 
		ID=286,
		Name="sWaitForDoAgain",
		DetailStr="稍等会儿才能再次使用此功能！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[287] = { 
		ID=287,
		Name="sPlayerCanotTransmit",
		DetailStr="{0} 不允许传送！！！",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[288] = { 
		ID=288,
		Name="sMagicShieldTime",
		DetailStr="你被附加了魔法盾，{0}秒后消失",
		Desc="时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[289] = { 
		ID=289,
		Name="sFarCartXY",
		DetailStr="你离镖车距离太远.当前它的坐标是[{0}({1}:{2})]",
		Desc="地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[290] = { 
		ID=290,
		Name="sNPCReloadOK",
		DetailStr="{0}重新加载成功...",
		Desc="NPC名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[291] = { 
		ID=291,
		Name="sAttackSkill",
		DetailStr="方向:{0} 技能类型:{1}",
		Desc="方向，技能ID",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[292] = { 
		ID=292,
		Name="sPermissionNotEnough",
		DetailStr="权限不够...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[293] = { 
		ID=293,
		Name="sPlayerOfflineOrOtherServer",
		DetailStr="{0} 现在不在线，或在其它服务器上！！！",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[294] = { 
		ID=294,
		Name="sCmdFormatOfOneParam",
		DetailStr="命令格式: @{0} {1}",
		Desc="命令名，参数1",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[295] = { 
		ID=295,
		Name="sItemNameCount",
		DetailStr="物品名称  数量",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[296] = { 
		ID=296,
		Name="sItemNameError",
		DetailStr="{0} 物品名称不正确！！！",
		Desc="物品名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[297] = { 
		ID=297,
		Name="sCanotMoveToMapXY",
		DetailStr="无法移动到地图: {0} X:{1} Y:{2}",
		Desc="地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[298] = { 
		ID=298,
		Name="sMonNameCountLevel",
		DetailStr="怪物名称 数量 等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[299] = { 
		ID=299,
		Name="sMonNameErrorOrOther",
		DetailStr="怪物名称不正确或其它未知问题！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[300] = { 
		ID=300,
		Name="sOverSpeed",
		DetailStr="[游戏超速] {0} 间隔:{1} 数量:{2}",
		Desc="fsdaf",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[301] = { 
		ID=301,
		Name="sMapID",
		DetailStr="地图号",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[302] = { 
		ID=302,
		Name="sCmdNeedFaceToNPC",
		DetailStr="命令使用方法不正确，必须与NPC面对面，才能使用此命令！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[303] = { 
		ID=303,
		Name="sOpenVIPFunction",
		DetailStr="打开会员功能窗口.",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[304] = { 
		ID=304,
		Name="sCmdFormatOfMission",
		DetailStr="命令格式: @{0} X  Y",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[305] = { 
		ID=305,
		Name="sMonTargetTo",
		DetailStr="怪物集中目标已设定为: {0}({1}:{2})",
		Desc="地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[306] = { 
		ID=306,
		Name="sCmdFormatOfMobPlace",
		DetailStr="命令格式: @{0} X  Y 怪物名称 怪物数量",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[307] = { 
		ID=307,
		Name="sNoMonTarget",
		DetailStr="还没有设定怪物集中点！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[308] = { 
		ID=308,
		Name="sSetMonTargetFirst",
		DetailStr="请先用命令{0}设置怪物的集中点。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[309] = { 
		ID=309,
		Name="sMonFocusingToTarget",
		DetailStr="{0}只 {1} 已正在往地图 {2} ({3}:{4}) 集中。",
		Desc="数量，怪物名称，地图名，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[310] = { 
		ID=310,
		Name="sForbidCmdInMap",
		DetailStr="此地图禁止使用此命令！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[311] = { 
		ID=311,
		Name="sCanotUseFunction",
		DetailStr="您现在还无法使用此功能！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[312] = { 
		ID=312,
		Name="sCmdFormatOfAddGuild",
		DetailStr="命令格式: @{0} 门派名称 掌门人名称",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[313] = { 
		ID=313,
		Name="sOnlyUseInMainServer",
		DetailStr="这个命令只能使用在主服务器上",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[314] = { 
		ID=314,
		Name="sCmdFormatOfMasterRecall",
		DetailStr="命令格式: @{0} (师徒传送，师父可以将徒弟传送到自己身边，徒弟必须允许传送。)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[315] = { 
		ID=315,
		Name="sGuildMaster",
		DetailStr="门派名称: {0} 掌门人: {1}",
		Desc="行会名，会长名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[316] = { 
		ID=316,
		Name="sCmdFormatOfAdjuestExp",
		DetailStr="命令格式: @{0} 人物名称 经验值",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[317] = { 
		ID=317,
		Name="sAdjuestExpOK",
		DetailStr="{0} 经验调整完成。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[318] = { 
		ID=318,
		Name="sCmdFormatOfAdjuestLevel",
		DetailStr="命令格式: @{0} 人物名称 等级",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[319] = { 
		ID=319,
		Name="sAdjuestLevelOK",
		DetailStr="{0} 等级调整完成。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[320] = { 
		ID=320,
		Name="sCmdFormatOfBackStep",
		DetailStr="命令格式: @{0} 人物名称",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[321] = { 
		ID=321,
		Name="sBackOneStep",
		DetailStr="{0} 后退了一格。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[322] = { 
		ID=322,
		Name="sBackStep",
		DetailStr="{0} 后退了。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[323] = { 
		ID=323,
		Name="sCmdFormatOfBonuPoint",
		DetailStr="命令格式: @{0} 人物名称 属性点数(不输入为查看点数)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[324] = { 
		ID=324,
		Name="sPlayerBonusPoint",
		DetailStr="{0} 的属性点数为: {1}",
		Desc="玩家名，属性值",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[325] = { 
		ID=325,
		Name="sCmdFormatOfChangeGender",
		DetailStr="命令格式: @{0} 人物名称 性别(男、女)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[326] = { 
		ID=326,
		Name="sPlayerChangeGenderOK",
		DetailStr="{0} 的性别已改变。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[327] = { 
		ID=327,
		Name="sPlayerChangeGenderFail",
		DetailStr="{0} 的性别未改变。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[328] = { 
		ID=328,
		Name="sBagFullNeedClear",
		DetailStr="背包已满，清理背包(@{0})",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[329] = { 
		ID=329,
		Name="sCmdFormatOfClearMapMonster",
		DetailStr="命令格式: @{0} 地图号(* 为所有) 怪物名称(* 为所有) 掉物品(0,1)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[330] = { 
		ID=330,
		Name="sMapNotExist",
		DetailStr="输入的地图不存在！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[331] = { 
		ID=331,
		Name="sClearMonCount",
		DetailStr="已清除怪物数: {0}",
		Desc="怪物数量",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[332] = { 
		ID=332,
		Name="sCmdFormatOfDearRecall",
		DetailStr="命令格式: @{0} (夫妻传送，将对方传送到自己身边，对方必须允许传送。)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[333] = { 
		ID=333,
		Name="sCanotDearRecallInMap",
		DetailStr="本地图禁止夫妻传送！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[334] = { 
		ID=334,
		Name="sCmdFormatOfDelBonuPoint",
		DetailStr="命令格式: @{0} 人物名称",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[335] = { 
		ID=335,
		Name="sDelBonuPointOK",
		DetailStr="{0} 的分配点数已清除！！！",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[336] = { 
		ID=336,
		Name="sCmdFormatOfDelDenyCharNameLogon",
		DetailStr="命令格式: @{0} 人物名称",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[337] = { 
		ID=337,
		Name="sDelDenyCharNameLogonOK",
		DetailStr="{0} 已从禁止登录人物列表中删除。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[338] = { 
		ID=338,
		Name="sDelDenyCharNameLogonFail",
		DetailStr="{0} 没有被禁止登录。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[339] = { 
		ID=339,
		Name="sCmdFormatOfDeleteItem",
		DetailStr="命令格式: @{0} 人物名称 物品名称 数量)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[340] = { 
		ID=340,
		Name="sDelGuildOnlyInMainServer",
		DetailStr="只能在主服务器上才可以使用此命令删除门派！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[341] = { 
		ID=341,
		Name="sCmdFormatOfDelGuild",
		DetailStr="命令格式: @{0} 门派名称",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[342] = { 
		ID=342,
		Name="sGuildNotFound",
		DetailStr="没找到{0}这个门派！！！",
		Desc="行会名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[343] = { 
		ID=343,
		Name="sDelNPCOK",
		DetailStr="删除NPC成功...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[344] = { 
		ID=344,
		Name="sCmdFormatOfDelSkill",
		DetailStr="命令格式: @{0} 人物名称 技能名称",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[345] = { 
		ID=345,
		Name="sCmdFormatOfDenyCharNameLogon",
		DetailStr="命令格式: @{0} 人物名称 是否永久封(0,1)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[346] = { 
		ID=346,
		Name="sAddToDenyListOK",
		DetailStr="{0} 已加入禁止人物列表",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[347] = { 
		ID=347,
		Name="sAddToTempDenyListOK",
		DetailStr="{0} 已加入临时禁止人物列表",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[348] = { 
		ID=348,
		Name="sTextFilterEnableOrDisable",
		DetailStr="启用/禁止文字过滤功能。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[349] = { 
		ID=349,
		Name="sTextFilterEnable",
		DetailStr="已启用文字过滤。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[350] = { 
		ID=350,
		Name="sTextFilterDisable",
		DetailStr="已禁止文字过滤。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[351] = { 
		ID=351,
		Name="sOutOfGuild",
		DetailStr="你已经退出门派。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[352] = { 
		ID=352,
		Name="sMasterCanotLeaveGuild",
		DetailStr="门派掌门人不能这样退出门派！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[353] = { 
		ID=353,
		Name="sNotInGuild",
		DetailStr="你都没加入门派！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[354] = { 
		ID=354,
		Name="sCmdFormatOfChangeSabukLord",
		DetailStr="命令格式: @{0} 城堡名称 门派名称",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[355] = { 
		ID=355,
		Name="sCastleLordClearOK",
		DetailStr="{0} 归属已清除",
		Desc="沙巴克城名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[356] = { 
		ID=356,
		Name="sCastleGuildChangeOK",
		DetailStr="{0} 所属门派已经更改为  {1}",
		Desc="沙巴克城名，行会名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[357] = { 
		ID=357,
		Name="sCastleNotFound",
		DetailStr="城堡未找到！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[358] = { 
		ID=358,
		Name="sPlayerCanotTransmitInMap",
		DetailStr="{0} 所在地图禁止传送。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[359] = { 
		ID=359,
		Name="sPlayerCanotGroupTransmit",
		DetailStr="{0} 禁止组队传送。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[360] = { 
		ID=360,
		Name="sCanUseAfterSecond",
		DetailStr="{0} 秒后才能使用此功能！！！",
		Desc="时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[361] = { 
		ID=361,
		Name="sCmdDetailOfGuildRecall",
		DetailStr="命令功能: 门派传送，门派掌门人可以将整个门派成员全部集中。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[362] = { 
		ID=362,
		Name="sCanUseByGuildMaster",
		DetailStr="门派掌门人才可以使用此功能！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[363] = { 
		ID=363,
		Name="sForbidCmdInCastleWar",
		DetailStr="攻城区域不允许使用此功能！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[364] = { 
		ID=364,
		Name="sPlayerCanotGuildTransmit",
		DetailStr="{0} 不允许门派传送！！！",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[365] = { 
		ID=365,
		Name="sGuildTransmitCount",
		DetailStr="已传送 {0} 个成员，{1} 个成员未被传送。",
		Desc="传送成员数，未传送成员数",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[366] = { 
		ID=366,
		Name="sCmdFormatOfHair",
		DetailStr="命令格式: @{0} 人物名称 类型值",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[367] = { 
		ID=367,
		Name="sHairChangeOK",
		DetailStr="{0}  的头发已改变。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[368] = { 
		ID=368,
		Name="sCmdErrorNeedFaceTo",
		DetailStr="命令使用方法不正确，必须与角色面对面站好！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[369] = { 
		ID=369,
		Name="sCmdDetailOfSearchDear",
		DetailStr="此命令用于查询配偶当前所在位置。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[370] = { 
		ID=370,
		Name="sCmdFormatOfSearchHuman",
		DetailStr="命令格式: @{0} 人物名称",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[371] = { 
		ID=371,
		Name="sPlayerPosition",
		DetailStr="{0} 现在位于{1}({2}:{3})",
		Desc="玩家名，地图ID，X坐标，Y坐标",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[372] = { 
		ID=372,
		Name="sCmdDetailOfSearchMaster",
		DetailStr="此命令用于查询师徒当前所在位置。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[373] = { 
		ID=373,
		Name="sPlayerOpenLogOK",
		DetailStr="{0} 开启日志",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[374] = { 
		ID=374,
		Name="sPlayerCloseLogOK",
		DetailStr="{0} 关闭日志",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[375] = { 
		ID=375,
		Name="sPlayerNoFound",
		DetailStr="{0} 玩家未找到",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[376] = { 
		ID=376,
		Name="sPermissionChangeOK",
		DetailStr="[权限调整] {0} ({1} {2} -> {3})",
		Desc="操作者玩家名，玩家名，原来权限值，修改后的权限值",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[377] = { 
		ID=377,
		Name="sCmdFormatOfSetPermission",
		DetailStr="命令格式: @{0} 人物名称 权限等级(0 - 10)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[378] = { 
		ID=378,
		Name="sDenyLoginListEmpty",
		DetailStr="禁止登录角色列表为空。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[379] = { 
		ID=379,
		Name="sCmdFormatOfHunger",
		DetailStr="命令格式: @{0} 人物名称 能量值",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[380] = { 
		ID=380,
		Name="sHungerChangeOK",
		DetailStr="{0} 的能量值已改变。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[381] = { 
		ID=381,
		Name="sNotHaveItem",
		DetailStr="身上没指定物品！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[382] = { 
		ID=382,
		Name="sCmdDetailOfSpirtStart",
		DetailStr="此命令用于开始祈祷生效宝宝叛变。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[383] = { 
		ID=383,
		Name="sSpirtStartTime",
		DetailStr="祈祷叛变已开始。持续时长 {0} 秒。",
		Desc="时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[384] = { 
		ID=384,
		Name="sCmdDetailOfSpirtStop",
		DetailStr="此命令用于停止祈祷生效导致宝宝叛变。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[385] = { 
		ID=385,
		Name="sSpirtStopOK",
		DetailStr="祈祷叛变已停止。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[386] = { 
		ID=386,
		Name="sCmdFormatOfStartQuest",
		DetailStr="命令格式: @{0} 问答名称",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[387] = { 
		ID=387,
		Name="sCmdFormatOfTestStatus",
		DetailStr="命令格式: @{0} 类型(0..11) 时长",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[388] = { 
		ID=388,
		Name="sTestStatusTime",
		DetailStr="状态编号:{0} 时间长度: {1} 秒",
		Desc="状态编号，时长秒",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[389] = { 
		ID=389,
		Name="sCmdFormatOfTrainingMagic",
		DetailStr="命令格式: @{0} 人物名称  技能名称 修炼等级(0-3)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[390] = { 
		ID=390,
		Name="sMagicNameErr",
		DetailStr="{0} 技能名称不正确！！！",
		Desc="技能名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[391] = { 
		ID=391,
		Name="sMagicTrained",
		DetailStr="{0} 技能已修炼过了！！",
		Desc="技能名称",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[392] = { 
		ID=392,
		Name="sCmdFormatOfTrainingSkill",
		DetailStr="命令格式: @{0} 人物名称  技能名称 修炼等级(0-3)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[393] = { 
		ID=393,
		Name="sReAliveOK",
		DetailStr="{0} 已获重生。",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[394] = { 
		ID=394,
		Name="sManagerListReloadOK",
		DetailStr="管理员列表重新加载成功...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[395] = { 
		ID=395,
		Name="sQMReloadOK",
		DetailStr="重新加载登录脚本完成...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[396] = { 
		ID=396,
		Name="sQFReloadOK",
		DetailStr="重新加载功能脚本完成...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[397] = { 
		ID=397,
		Name="sMonItemReloadOK",
		DetailStr="怪物爆物品列表重加载完成...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[398] = { 
		ID=398,
		Name="sMonItemReloadFail",
		DetailStr="怪物爆物品列表重加载失败！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[399] = { 
		ID=399,
		Name="sRobotConfigReloadOK",
		DetailStr="重新加载机器人配置完成...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[400] = { 
		ID=400,
		Name="sRobotManagerReloadOK",
		DetailStr="重新加载机器人专用脚本完成...",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[401] = { 
		ID=401,
		Name="sCmdFormatOfReNewLevel",
		DetailStr="命令格式: @{0} 人物名称 点数(为空则查看)",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[402] = { 
		ID=402,
		Name="sPlayerReLevel",
		DetailStr="{0} 的转职等级为 {1}",
		Desc="玩家名，转职等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[403] = { 
		ID=403,
		Name="sCmdFormatOfRestBonuPoint",
		DetailStr="命令格式: @{0} 人物名称",
		Desc="命令名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[404] = { 
		ID=404,
		Name="sBonusPointReset",
		DetailStr="分配点数已复位！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[405] = { 
		ID=405,
		Name="sPlayerBonusPointReset",
		DetailStr="{0} 的分配点数已复位.",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[406] = { 
		ID=406,
		Name="sPlayerPermission",
		DetailStr="{0} 当前权限为: {1}",
		Desc="玩家名，权限值",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[407] = { 
		ID=407,
		Name="sNotCastleNPC",
		DetailStr="NPC不属于城堡！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[408] = { 
		ID=408,
		Name="sRepairOK",
		DetailStr="修理成功。",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[409] = { 
		ID=409,
		Name="sCastleDoorNotNeedRepair",
		DetailStr="城门不需要修理！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[410] = { 
		ID=410,
		Name="sCastleWallNotNeedRepair",
		DetailStr="城墙不需要修理！！！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[411] = { 
		ID=411,
		Name="sCanotSendmsg",
		DetailStr="{0}无法发送信息.",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[412] = { 
		ID=412,
		Name="sUserDenyWhisperMsg",
		DetailStr="{0}拒绝私聊！！！",
		Desc="玩家名",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[413] = { 
		ID=413,
		Name="sYouNeedLevelMsg",
		DetailStr="{0}级后才可以发送喊话消息！！！",
		Desc="等级",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[414] = { 
		ID=414,
		Name="sJoinGuildCoolHint",
		DetailStr="退出门派后，需要{0}分钟后才能再次进入门派!",
		Desc="剩余加入时间",
		FColor=255,
		BColor=218,
		SendType=1,
	},
	[415] = { 
		ID=415,
		Name="sNoPlayer",
		DetailStr="玩家已离线！",
		FColor=255,
		BColor=218,
		SendType=1,
	},
}
return config
