
local SimpleNameMap = {
    ["KEY_PAUSE"]           = "Pause",
    ["KEY_SCROLL_LOCK"]     = "ScrollLock",
    ["KEY_PRINT"]           = "Print",
    ["KEY_SYSREQ"]          = "SysReq",
    ["KEY_BREAK"]           = "Break",
    ["KEY_ESCAPE"]          = "Esc",
    -- ["KEY_BACKSPACE"]       = "Backspace",
    ["KEY_TAB"]             = "Tab",
    ["KEY_RETURN"]          = "Enter",
    ["KEY_CAPS_LOCK"]       = "CapsLock",
    ["KEY_SHIFT"]           = "Shift",
    ["KEY_CTRL"]            = "Ctrl",
    ["KEY_ALT"]             = "Alt",
    -- ["KEY_RIGHT_SHIFT"]     = "Shift",
    -- ["KEY_RIGHT_CTRL"]      = "Ctrl",
    -- ["KEY_RIGHT_ALT"]       = "Alt",
    ["KEY_MENU"]            = "Menu",
    ["KEY_INSERT"]          = "Insert",
    ["KEY_HOME"]            = "Home",
    ["KEY_PG_UP"]           = "PageUp",
    -- ["KEY_DELETE"]          = "Delete",
    ["KEY_END"]             = "End",
    ["KEY_PG_DOWN"]         = "PageDown",
    ["KEY_LEFT_ARROW"]      = "←",
    ["KEY_RIGHT_ARROW"]     = "→",
    ["KEY_UP_ARROW"]        = "↑",
    ["KEY_DOWN_ARROW"]      = "↓",
    ["KEY_NUM_LOCK"]        = "Numlock",
    ["KEY_KP_PLUS"]         = "数字键盘+",
    ["KEY_KP_MINUS"]        = "数字键盘-",
    ["KEY_KP_MULTIPLY"]     = "数字键盘*",
    ["KEY_KP_DIVIDE"]       = "数字键盘/",
    ["KEY_KP_ENTER"]        = "数字键盘Enter",
    ["KEY_KP_INSERT"]       = "数字键盘0",
    ["KEY_KP_END"]          = "数字键盘1",
    ["KEY_KP_DOWN"]         = "数字键盘2",
    ["KEY_KP_PG_DOWN"]      = "数字键盘3",
    ["KEY_KP_LEFT"]         = "数字键盘4",
    ["KEY_KP_FIVE"]         = "数字键盘5",
    ["KEY_KP_RIGHT"]        = "数字键盘6",
    ["KEY_KP_HOME"]         = "数字键盘7",
    ["KEY_KP_UP"]           = "数字键盘8",
    ["KEY_KP_PG_UP"]        = "数字键盘9",
    ["KEY_KP_DELETE"]       = "数字键盘.",
    ["KEY_F1"]              = "F1",
    ["KEY_F2"]              = "F2",
    ["KEY_F3"]              = "F3",
    ["KEY_F4"]              = "F4",
    ["KEY_F5"]              = "F5",
    ["KEY_F6"]              = "F6",
    ["KEY_F7"]              = "F7",
    ["KEY_F8"]              = "F8",
    ["KEY_F9"]              = "F9",
    ["KEY_F10"]             = "F10",
    ["KEY_F11"]             = "F11",
    ["KEY_F12"]             = "F12",
    ["KEY_SPACE"]           = "Space",
    ["KEY_EXCLAM"]          = "Exclaim",
    ["KEY_QUOTE"]           = "Quote",
    ["KEY_DOLLAR"]          = "Dollar",
    ["KEY_PERCENT"]         = "Percent",
    ["KEY_AMPERSAND"]       = "Ampersand",
    ["KEY_LEFT_PARENTHESIS"] = "LeftParen",
    ["KEY_RIGHT_PARENTHESIS"] = "RightParen",
    ["KEY_ASTERISK"]        = "Asterisk",
    ["KEY_PLUS"]            = "Plus",
    ["KEY_COMMA"]           = "Comma",
    ["KEY_MINUS"]           = "Minus",
    ["KEY_PERIOD"]          = "Period",
    ["KEY_SLASH"]           = "Slash",
    ["KEY_0"]               = "0",
    ["KEY_1"]               = "1",
    ["KEY_2"]               = "2",
    ["KEY_3"]               = "3",
    ["KEY_4"]               = "4",
    ["KEY_5"]               = "5",
    ["KEY_6"]               = "6",
    ["KEY_7"]               = "7",
    ["KEY_8"]               = "8",
    ["KEY_9"]               = "9",
    ["KEY_COLON"]           = "Colon",
    ["KEY_SEMICOLON"]       = "Semicolon",
    ["KEY_LESS_THAN"]       = "Less",
    ["KEY_EQUAL"]           = "Equals",
    ["KEY_GREATER_THAN"]    = "Greater",
    ["KEY_QUESTION"]        = "Question",
    ["KEY_AT"]              = "At",
    ["KEY_LEFT_BRACKET"]    = "[",
    ["KEY_BACK_SLASH"]      = "\\",
    ["KEY_RIGHT_BRACKET"]   = "]",
    ["KEY_UNDERSCORE"]      = "-",
    ["KEY_A"]               = "A",
    ["KEY_B"]               = "B",
    ["KEY_C"]               = "C",
    ["KEY_D"]               = "D",
    ["KEY_E"]               = "E",
    ["KEY_F"]               = "F",
    ["KEY_G"]               = "G",
    ["KEY_H"]               = "H",
    ["KEY_I"]               = "I",
    ["KEY_J"]               = "J",
    ["KEY_K"]               = "K",
    ["KEY_L"]               = "L",
    ["KEY_M"]               = "M",
    ["KEY_N"]               = "N",
    ["KEY_O"]               = "O",
    ["KEY_P"]               = "P",
    ["KEY_Q"]               = "Q",
    ["KEY_R"]               = "R",
    ["KEY_S"]               = "S",
    ["KEY_T"]               = "T",
    ["KEY_U"]               = "U",
    ["KEY_V"]               = "V",
    ["KEY_W"]               = "W",
    ["KEY_X"]               = "X",
    ["KEY_Y"]               = "Y",
    ["KEY_Z"]               = "Z",
    ["KEY_LEFT_BRACE"]      = "{",
    ["KEY_BAR"]             = "|",
    ["KEY_RIGHT_BRACE"]     = "}",
    ["KEY_TILDE"]           = "`",
    ["KEY_ENTER"]           = "Enter",
    ["MOUSE_0"]             = "鼠标左键",
    ["MOUSE_1"]             = "鼠标右键",
    ["MOUSE_2"]             = "鼠标中键",
    -- ["MOUSE_3"]             = "鼠标键3",
    -- ["MOUSE_4"]             = "鼠标键4",
    -- ["MOUSE_5"]             = "鼠标键5",
    -- ["MOUSE_6"]             = "鼠标键6",
}

local fullNameMap = {}

local function Init()
    for k, v in pairs(SimpleNameMap) do
        fullNameMap[v] = k
    end
    SimpleNameMap["KEY_RIGHT_SHIFT"] = "Shift"
    SimpleNameMap["KEY_RIGHT_CTRL"] = "Ctrl"
    SimpleNameMap["KEY_RIGHT_ALT"] = "Alt"
end
Init()

local SettingKeyName = {}

-- (此接口也代表可注册的快捷键)
function SettingKeyName.GetSimpleKeyName(fullKeyName)
    return SimpleNameMap[fullKeyName]
end
function SettingKeyName.GetFullKeyName(fullKeyName)
    return fullNameMap[fullKeyName]
end


return SettingKeyName