local config = { 
	[1] = { 
		ID=1,
		Name="主要描述",
		NameShow=0,
		AttrType="内容对应Item表和ItemEquip表的Desc字段",
	},
	[2] = { 
		ID=2,
		Name="基础属性",
		NameShow=0,
		AttrType="内容对应ItemEquip表的Attribute字段",
	},
	[3] = { 
		ID=3,
		Name="自定义属性",
		NameShow=0,
	},
	[4] = { 
		ID=4,
		Name="套装属性",
		NameShow=1,
	},
	[5] = { 
		ID=5,
		Name="物品来源：",
		NameShow=0,
	},
	[11] = { 
		ID=11,
		Name="新模块例子1",
		NameShow=0,
		ValuesEx="0#1#2#3#4#5",
		AttrType="内容对应Item表和ItemEquip表的ConditionId字段",
	},
	[13] = { 
		ID=13,
		Name="合成石属性",
		NameShow=1,
		AttrType="内容对应Item表的Attribute字段",
	},
	[14] = { 
		ID=14,
		Name="获取途径：",
		NameShow=1,
		AttrType="内容对应Item表和ItemEquip表的GetWayInfo字段",
	},
	[15] = { 
		ID=15,
		Name="职业：",
		NameShow=1,
		AttrType="内容对应ItemEquip表的TransferID字段",
	},
	[16] = { 
		ID=16,
		Name="职业名：",
		NameShow=1,
		AttrType="内容对应ItemEquip表的TransferID字段",
	},
	[17] = { 
		ID=17,
		Name="等级：",
		NameShow=1,
		AttrType="内容对应ItemEquip表的Need字段",
	},
	[18] = { 
		ID=18,
		Name="品级：",
		NameShow=0,
		AttrType="内容对应Item表和ItemEquip表的Grade字段",
	},
	[19] = { 
		ID=19,
		Name="阵营：",
		NameShow=0,
		AttrType="内容对应ItemEquip表的TransferID字段",
	},
	[20] = { 
		ID=20,
		Name="热血币",
		NameShow=1,
		ValuesEx="9#17",
		AttrType="自定义参数指的是货币ID",
	},
	[21] = { 
		ID=21,
		Name="元宝",
		NameShow=0,
		ValuesEx="2#5",
		AttrType="自定义参数指的是货币ID",
	},
	[22] = { 
		ID=22,
		Name="性别：",
		NameShow=1,
		AttrType="内容对应ItemEquip表的Gender字段",
	},
	[23] = { 
		ID=23,
		Name="合成石",
		NameShow=1,
		AttrType="内容对应ItemEquip表的SyntheticStone字段，装备上合成石的孔位",
	},
	[24] = { 
		ID=24,
		Name="装置：",
		NameShow=1,
		AttrType="内容对应ItemEquip表的StdMode字段，取ItemEquiPos中的Desc文字",
	},
	[25] = { 
		ID=25,
		Name="生命剩余恢复总量：",
		NameShow=1,
		AttrType="内容对应Item表的DuraMax字段",
	},
	[26] = { 
		ID=26,
		Name="内力剩余恢复总量：",
		NameShow=1,
		AttrType="内容对应Item表的DuraMax字段",
	},
	[27] = { 
		ID=27,
		Name="气功等级",
		NameShow=0,
		AttrType="内容对应Item表和ItemEquip表的nQiGongId、nQiGongLv字段",
	},
	[101] = { 
		ID=101,
		Name="武勋自定义属性",
		NameShow=0,
	},
}
return config
